### ISSUE TITLE
Automatical download of Faceit and ESEA demos.

### ISSUE THREAD

**Issue by ma-karai** [akiver/cs-demo-manager#140]
Is there a way to implement this? 

It would also be fantastic to follow the "ELO" progress on faceit, and even display the ELO for the individual player

**Comment by 0BuRner** [comment]
Should be pretty simple to get FaceIT ELO thx to their API (seems not totally public), here is a request example : https://api.faceit.com/api/nicknames/BuRner
Return a simple JSON to parse. API key not needed, at least for one request.
More infos here : https://www.reddit.com/r/GlobalOffensive/comments/53mwsd/check_your_faceit_elo_faceitstatscom/

**Comment by StrPlayer** [comment]
will this ever be implemented

**Comment by ma-karai** [comment]
Well, its open since 2016....

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
