### ISSUE TITLE
Suggestion: Support CS 1.x and CSS Demos.

### ISSUE THREAD

**Issue by rafaelfborges** [akiver/cs-demo-manager#157]
What's up. First, I would like to thank you for this amazing tool and the hours of dedication spent on making this program better. My suggestion is simple, there is some possibility of this software compatibility with the demos of CS 1.x and CSS? That would be fantastic. There were some programs in the past, such as "SK Demo Player" and "coL demo player", but went ahead and were discontinued. Searching recently, I found a tool called "Demofreak" but the last update is dated 17/04/2004. Support help several moviemakers to write or rewrite historical plays with high quality.

Thank you for your attention.

**Comment by Calak** [comment]
It's a (almost) completely different protocol. So,  this tool will never be compatible with 1.x/source until someone recode the entire parsing job for them.

**Comment by akiver** [comment]
It requires a lot of work, I personally will not work on it sorry.
I keep the issue open if someone wants to do it.

**Comment by 0BuRner** [comment]
If I not mistaken, coL Demo Player is open source and written in C# too.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
