### ISSUE TITLE
[Request] Additional Clutch Variables and Statistics

### ISSUE THREAD

**Issue by BlakeJagged** [akiver/cs-demo-manager#168]
Wins by default (out of time and bomb explosions) or hostage rescue counting as a clutch.

Also having clutch stats on the overall stats page like the kills (2k,3k,4k,5k,) (1v1,1v2,1v3,1v4,1v5)

**Comment by BlakeJagged** [comment]
Also, on game summary where it has all the kills lined up and says if it was a headshot also say if it was a wallbang? This would be a great tool for me making fragmovies and many other content creators.

**Comment by BlakeJagged** [comment]
"Load All" button or higher amount than 50

**Comment by BlakeJagged** [comment]
Rename Feature

**Comment by BlakeJagged** [comment]
Headshot Ratio (or ammount) on the main demos overview page

**Comment by BlakeJagged** [comment]
Average RWS and  entry / hold kill success %'s

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
