### ISSUE TITLE
Document / Explain the sheets in individual match exports 

### ISSUE THREAD

**Issue by ReagentX** [akiver/cs-demo-manager#171]
How are the values in these sheets determined? What determines an "Entry Hold Kill" and an "Entry Kill" here?

- Entry Hold Kills Rounds
- Entry Hold Kills Players
- Entry Hold Kills Teams
- Entry Hold Kills Players
- Entry Kills Rounds
- Entry Kills Players
- Entry Kills Teams

**Comment by akiver** [comment]
Entry kill = First kill as T
Entry Hold Kill = First kill as CT

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
