### ISSUE TITLE
[Request] Sort Players by Team in the Flashbang stats

### ISSUE THREAD

**Issue by yorick-ne** [akiver/cs-demo-manager#179]
Currently i dont see a pattern in how the players are sorted in the who-flashed-who matrix. This makes it difficult to see how much one flashed their teammates/enemies sometimes. 
In theory this should make the who-flashed-who matrix look kinda like the matrix in the top right, with some variation per player.

The teams themselves should probably be sorted in the same way as on the top right to stay consistent.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
