### ISSUE TITLE
First round is not always labeled as round 1 in ebot demos

### ISSUE THREAD

**Issue by ReagentX** [akiver/cs-demo-manager#218]
http://www.hltv.org/match/2301161-e-fragnet-faze-iem-katowice-2016

The first round of this match is detected as round 3 for some reason.

**Comment by ReagentX** [comment]
http://www.hltv.org/match/2306090-immortals-mousesports-esl-pro-league-season-4-finals Same with this demo except it is detected as round 2.

**Comment by ReagentX** [comment]
Upon further investigation, this issue only occurs with ebot demos. See http://www.hltv.org/match/2306676-cloud9-nip-iem-oakland-2016 and http://www.hltv.org/?pageid=28&demoid=24966 (Train from the BO3.)

**Comment by ReagentX** [comment]
Some matches have incorrect scores i.e. the last two linked above. Most ebot demos work perfectly, however, many of them result in incorrect data.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
