### ISSUE TITLE
Add rounds "timeline"

### ISSUE THREAD

**Issue by 0BuRner** [akiver/cs-demo-manager#23]
Could be great to have a rounds "timeline" like this http://cevo.com/hub/csgo/pug/111639/ showing on two lines the winner of each round with icons following the reason of the round end.
With tooltip or number on each showing the number of player alive left is a plus.

**Comment by Vipitis** [comment]
additional idea: a full timeline where x is the tickrate of the demo in lenear increments and it highlits all your actions...

**Comment by 0BuRner** [comment]
Here are some more related ideas : https://csgostats.gg/match/55547

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
