### ISSUE TITLE
Decoupling demo analyzer from GUI dependency

### ISSUE THREAD

**Issue by dangmai** [akiver/cs-demo-manager#238]
Hi,

First of all let me say Thank you for creating the application, it is a wonderful tool that does a lot of things right and clearly has a lot of thoughts put into it.

I'm wondering if you think it would be beneficial if we decouple the Demo Analyzer part (basically the Core project) from the GUI dependency, maybe make it a .Net Standard library instead of .Net framework program, so that it can be used by other programs on different operating systems. Possible use cases may include: Command Line Interface to the program (maybe to print out JSON data for a demo file); cross platform access to the library so that other cross platform GUIs can be developed against the library.

I'm not quite sure how feasible it is to do it yet, but won't mind jumping in the code base to find out. But if you think it's not a good addition to the program I'll understand too 🥂

**Comment by n1c** [comment]
Just jumping in to say this is a great idea. I started a project to do exactly what you used as an example (command line tool to convert dem -> json but don't really have the .NET experience to make it happen myself.

**Comment by kpei** [comment]
I've recently started doing this and it isn't particularly hard.  The analyzer is packaged within Services/Concrete/Analyzer.  The only dependencies being Core and Demoinfo.  i am currently parsing demos through the console using the AnalyzeDemosAsync method within each analyzer and using the parsed `Demo` obj to write to file.  I think more sophisticated recording can be done by overriding the hooks for each analyzer.

**Comment by xpekt** [comment]
@kpei can you share what you have so far?

**Comment by master117** [comment]
Why don't you just write your own analyzer using demoinfogo? 

There is a 100% chances that you don't want exactly the same data from the demo as this program. So you would sacrifice speed and maintainability. 

You would also have to write something to convert the data in your own format.

Writing your own customized analyser sounds a lot easier.

**Comment by kpei** [comment]
@xpekt sure.  I used it for a very specific purpose so I'm only extracting parts of the data I'm interested in.

**Comment by xpekt** [comment]
i ended up doing it myself, but thank you @kpei

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
