### ISSUE TITLE
[Suggestion] Edit the Duels page to more accurately represent entries

### ISSUE THREAD

**Issue by DavidAllewell** [akiver/cs-demo-manager#241]
Been using this app for a while now, and something that has always frustrated me is how the "Duels" tab is handled in a Player's match details.

Currently, entry kills (EKs) are classed as any kill where the T gets the first kill of the round, with either the killer or victim being involved in said kill. Similarly for entry-hold kills (EHKs) and CT.

While this might be dictionary-correct, I don't consider this correct in the case where you are the victim of either an EK or an EHK.

[Here](http://i.imgur.com/u69223A.png) is a snapshot of my duels page from a recent match. Note that I was considered to have 5 EKs, which was reflected on the match details page. The first 4 EKs are fine, all of those were correct entries. My issue is with the kill that occurred on round 28. While I understand that this fits the definition of an EK (T kill first), I personally see this as a failed EHK, as I have failed to get the first kill of the round while on CT side, and lost my duel.

Similarly with the first 4 kills in EHK, I believe these should be considered failed EKs, as I have taken a duel as T side and lost, and therefore not converted my entry kill.

Hopefully I can see this changed! Cheers

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
