### ISSUE TITLE
[Bug] "Stuffs" not counting some rounds

### ISSUE THREAD

**Issue by msattam** [akiver/cs-demo-manager#247]
Some rounds do not have their nades being counted. It seems pretty random which ones they are, and I'm not sure why the round breakdowns show a nade being used but within the "stuffs" category it doesn't register it.

**Comment by ReagentX** [comment]
Please post an example demo with the rounds and what is not being counted.

**Comment by msattam** [comment]
I'm doing data work with flashes specifically for the PGL Major, and here have been some rounds where in the "stuffs" category there are not flashbangs being recorded, but within the round breakdown timeline there are:

Round 1 Game 1 - Gambit vs. Mouz - Round 25
R1G2 - Fnatic vs. F3 - Round 9
R1G3 - VP vs. Vega - Rond 7, 10, 11
R1G4 - SK vs. PENTA - Round 10
R1G5 - FaZe vs. BIG - Round 6 and 7

I also have 2 other suggestions I'd like to make about nades data, but I'll create new issues for them. 

Thank you for your work on this app! It's fantastic.

**Comment by Cookieseller** [comment]
The WeaponFired event seems to be triggered before the nade is actually thrown, if a throw is canceled it will still be in the NadeQueue and the WeaponFired and NadeExploded counts won't match up, resulting in all nades of the type not being evaluated. This could potentially be resolved by checking player equipment to see if a player still has the Nade after the event was triggered.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
