### ISSUE TITLE
[Suggestion] Make easy to find demo highlights

### ISSUE THREAD

**Issue by mifkys** [akiver/cs-demo-manager#248]
Hello! I started to use this is great tool to find professional players highlights from GOTV demos. Manager already has columns with 4K, 5K, 1vX situations but in current version need to do many clicks to find successful clutches. Maybe will it be useful in some way?

**Comment by akiver** [comment]
What do you propose?

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
