### ISSUE TITLE
Suggestion: Add ability to filter game stats by half

### ISSUE THREAD

**Issue by djmattyg007** [akiver/cs-demo-manager#277]
It would be useful to break down a game's statistics by which half they occurred on.

**Comment by cybersteel8** [comment]
Metrics aggregating performance in a half of a particular game to compare against the other half would be very useful. +1

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹

**Comment by andrewrogulkin** [comment]
I suppose it is possible to get first half overview in the map statistics, but cant find how to filter it, could you help me please?
