### ISSUE TITLE
[Enhancement] Multiple Recording Job System

### ISSUE THREAD

**Issue by Darkhandrob** [akiver/cs-demo-manager#286]
Instead of recording the demos one by one, a job system would be nice, where you set up multiple demos with your settings(starttick, endtick, player) and the programm records them one after the other. If you created and exported your mirv_campath beforehand, you could maybe also record the camera smooths with the raw gameplay of the demo automatically.

**Comment by djmattyg007** [comment]
This would be fantastic. Using the movie making functionality can take a very long time even for just 30 seconds of footage. It would be great to queue up several recordings and leave it to run overnight.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
