### ISSUE TITLE
Suggestion : Let us choose which data to show

### ISSUE THREAD

**Issue by JSadones** [akiver/cs-demo-manager#29]
Some information about a demo is unnecessary for me, so it takes up a lot of space.

So an option to disable "Hostname", "Type", "Client", .. would be nice.

Also when re-sizing these tables, they do not save for the next time you open the program.

**Comment by 0BuRner** [comment]
It already exists an option in the settings panel where you can check which column you want to see.
But you're right about the resizing, it doesn't save but that could be pretty cool.

**Comment by JSadones** [comment]
@0BuRner Thank you did not see this option in options.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
