### ISSUE TITLE
Time of Death improvements

### ISSUE THREAD

**Issue by Viigoo** [akiver/cs-demo-manager#295]
As it is now, there is a problem with calculating average time of death of a player, because players that rarely died in a game will usually have lower ATD (Average Time of Death) - which is opposite of expected outcome.

![atd_issue](https://user-images.githubusercontent.com/17125729/37540723-55f41f4e-2958-11e8-8c7e-283e97450fda.png)

This is because players that didn't die in a round have TD value (Time of Death) of 0. So in a sense it counts as "died immediately", because ATD takes into consideration those rounds.

![atd_issue2](https://user-images.githubusercontent.com/17125729/37540782-8e717920-2958-11e8-8e80-c927d5d40975.png)

Possible solutions to this problem:

a) Ignore rounds where TD = 0, while calculating ATD.
b) Instead of putting value 0 when player didn't die, put actual duration of a round (this can be misleading/counterintuitive though, because non-zero value can indicate that player actually died, which would not be the case).
c) Instead of using ATD and TD, use Survived Duration and Average Survived Duration. (Similiar to b) but more clear naming).

Personally I would choose variant **a**, as it seems to be the most prone to outlier observations.

--------------------------------------------------------------------------------------------------------

By the way, I thought that it also might be worth adding proportional ATD, because some games are quickier, some are slower. I.e. value of 30 ATD doesn't tell the full story (i.e. in slower games it's probably low).

So maybe a paremeter that show percentage of all rounds actual gameplay (not spectating other players). I.e. a value of 80% would indicate that 80% of time player was ingame, and 20% was dead.

**Comment by Cookieseller** [comment]
I think solution a would be counter intuitive as well. Consider this a player survives every round but one and dies within 5 seconds in that round. Now the ATD would be 5, even though he died only once. I would be in favor of solution c, but maybe somebody has a better idea to resolve this while keeping ATD.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
