### ISSUE TITLE
Different "Name"-column width for both teams in Details

### ISSUE THREAD

**Issue by S-Essig** [akiver/cs-demo-manager#312]
If you open the Details menu for any match, the  "Name"-column width for each Team is set by the longest name in each team. This makes the data comparison between players of different teams kind of awkward as all the rows behind "Name" are shifted from team to team.

Fix: Calculate and set the column width for "Name" from the longest name among all players.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
