### ISSUE TITLE
Utilise new data from Steam

### ISSUE THREAD

**Issue by be-an-adult** [akiver/cs-demo-manager#316]
Is there a way the application can begin to use the repository of data collected by steam to analyse all of our previous MM games?

**Comment by master117** [comment]
The "new" data is just the same data as previously available through the watchtab. You can only load the last 8 matches/demos, just like through the watchtab. And just some scoreboards won't give you much data. It can also not be accessed remotely, but only for the currently logged in user.

**Comment by be-an-adult** [comment]
I’m mainly curious if there’s a way to have CSGODM take all of those share codes en masse instead of importing each match one-by-one.

**Comment by master117** [comment]
>It can also not be accessed remotely, but only for the currently logged in user.

CSGODM would have to acess the steam page or api logged in as the user who wants to access it, thats probably doable, but will violate steams ToS.

**Comment by 0BuRner** [comment]
Even if using OAuth ?

**Comment by rHermes** [comment]
One new source of data that I really want is the ability to download wingman matches. The last demos are available on the new page and it's just a matter of getting the urls to download the demos.

I do not know if this would be against the TOS, but if not, it would really be a nice addition.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
