### ISSUE TITLE
CSGO Crashing after a while when watching demo

### ISSUE THREAD

**Issue by magnusvmt** [akiver/cs-demo-manager#320]
CSGO crashes after about 20 minutes of viewing the demo when started through demo manager. This does not happen when watching demos in CSGO when started through Steam. I've tried different graphic settings but nothing seems to help.

I can't find any debug logs. Any ideas?

**Comment by akiver** [comment]
There is no message when the crash occurs?
It happens with all demos?

CSGO DM only launch the game and indicates to the game to start the demo playback.

**Comment by magnusvmt** [comment]
No crash message it just closes. It happens with all demos started through demo manager and with no demos started through CSGO. 100% reproducible.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
