### ISSUE TITLE
Add wingman support

### ISSUE THREAD

**Issue by djmattyg007** [akiver/cs-demo-manager#324]
It's possible to download wingman demos through the Steam website now. It would be great if the program could do this and handle the fact that each system has its own rank. Right now if I manually import a wingman demo, it thinks my competitive rank has changed, and then changes straight back for the next competitive demo.

**Comment by wordlesswind** [comment]
I found that it seems that I can't export Wingman Mode Demo data.

Wingman Mode Demo
https://web.archive.org/web/20190205143659/http://replay187.valve.net/730/003327198011150303265_1154322371.dem.bz2

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
