### ISSUE TITLE
Maybe wrong Chinese character encode mode in groupname?

### ISSUE THREAD

**Issue by PulsarisDev** [akiver/cs-demo-manager#327]
I have joined a steam group which name is full of Chinese character. I recorded many demo using this groupname . When I open the demo via this software and click "Analysis" , The groupname in Chinese character won`t show in a right way. In my opinion, the encoding mode is the reason why cause this issue. There are many encoding method like UTF-8 , Unicode , GBK , GB2312 to show Chinese character, but maybe here got some issue?

Example:
![image](https://user-images.githubusercontent.com/18120120/41979919-cd4eeeac-7a57-11e8-93e7-6f7d406e366e.png)
The groupname here should be "人大♂附中 死宅势力"

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
