### ISSUE TITLE
[Suggestion] Add office completely in the statistics and in the details of games

### ISSUE THREAD

**Issue by XmatrixX97** [akiver/cs-demo-manager#336]
I play a lot of office but the map is not completely incorporated into the app so I can not see what my win percentage is and the total number of games played
![demos](https://user-images.githubusercontent.com/29832137/44372486-82cac800-a4ba-11e8-8f1f-d8799d286a47.png)

**Comment by CorySanin** [comment]
#347 might fix this I think

**Comment by akiver** [comment]
The version 2.13.5 includes office images and support for heatmaps.
If you are looking for stats such as hostage rescue it's not available.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
