### ISSUE TITLE
Demo watching/movie making not working with demos having dots characters in filenames

### ISSUE THREAD

**Issue by hacklex** [akiver/cs-demo-manager#341]
First of all, thank you for the amazing tool.

My initial filename was overpass.7.10.18.dem.
The file opened and was analyzed just fine, but the demo started from the warmup, and no recording was made.
After I renamed the file to just overpass.dem, the problem disappeared.

My guess on this is that – probably – it's actually csgo's fault, as it plainly ignored the accompanying vdm file because of reasons unknown to me, but linked with the file having too much dots in its name. Regardless of the fact, at least a notification to the users would be much appreciated, as not everyone have the technical background enough to trace the problem root back to the file name being suspicious (for csgo).

So, whenever opening a demo that has more than one dot character (.) in filename, it would be wise to either 
(a) silently make a properly named copy of the demo, and perform the recording/viewing of it instead of the original,
(b) just display a warning that the user would need to rename the file in order to watch highlights, make movies etc,
(c) offer the user to either rename the file as needed, make a temporary copy to work with, or go on with the badly named file, having no option to control the demo flow via vdm,
(d) pinpoint what would be the proper vdm file name csgo would seek, given the demo file name, and name the generated vdm file accordingly.

**Comment by akiver** [comment]
Yes this is a csgo limitation but warn the user is a possible option

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
