### ISSUE TITLE
Doesn't recognize well custom pugs with knife rounds

### ISSUE THREAD

**Issue by borzaka** [akiver/cs-demo-manager#372]
The server used [PugSetup](https://github.com/splewis/csgo-pug-setup) with knife rounds.

With different sources before clicking to analyze, different outcome occurs.

Source: PopFlash
![image](https://user-images.githubusercontent.com/1230402/56701247-55e04c00-66fe-11e9-9963-b1f0c900e5dc.png)
The round counter is wrong.

Good team won:
![image](https://user-images.githubusercontent.com/1230402/56701254-61337780-66fe-11e9-9c46-6deefc2d5407.png)
Good side scores.

Source: ESEA
![image](https://user-images.githubusercontent.com/1230402/56701229-39dcaa80-66fe-11e9-8814-9ab71f00a8c0.png)
Good round counter.

Wrong team won:
![image](https://user-images.githubusercontent.com/1230402/56701234-46610300-66fe-11e9-8444-83fe02797ecd.png)
Wrong side scores.

Other sources just doesn't work.

**Comment by iebb** [comment]
Try this: https://github.com/iebb/CSGO-Demos-Manager/releases/tag/2.11.2%2Bpugsetup

**Comment by akiver** [comment]
PugSetup has never been supported and will not in a near future.

**Comment by borzaka** [comment]
It's pity, because it's very simple:
1. warmup
2. knife round (or not)
2.1 switching sides (or not, team stays)
3. some restarts
4. live

**Comment by akiver** [comment]
PR are welcome

**Comment by 0BuRner** [comment]
PR already exists for PugSetup demos #375

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
