### ISSUE TITLE
Only grenades are exported to JSON object WeaponFired

### ISSUE THREAD

**Issue by Viigoo** [akiver/cs-demo-manager#374]
In class Services.Concrete.Analyzer.DemoAnalyzer.
Line number 808:
```c#
if (e.Weapon.Class == EquipmentClass.Grenade) {
    Application.Current.Dispatcher.Invoke(() => CurrentRound.WeaponFired.Add(shoot));
}
```
I'm not sure wheter equality condition was intended, but other weapons fired (like rifles) are never exported. On a screenshot below you can see weapon_fired object that contains 3 entries, which correspond to flashbangs_exploded, smokes_started, he_exploded

![image](https://user-images.githubusercontent.com/17125729/57568005-9966d580-73e1-11e9-8a2d-fd12ed5676d8.png)

**Comment by akiver** [comment]
This is a technical and app history issue, all shots except grenades are ignored because it will increase disk / RAM usage since data are stored as json and the (poor) 2D overview feature doesn't draw shots from weapons other than grenades.  
But it could definitely be re-worked.

**Comment by akiver** [comment]
The next version will export all weapon fire events.
The field `weapon_fired` of each round will still contain only grenades, it's not perfect but you can use the global field `weapon_fired` and filter on a specific round using `round_number`.
