### ISSUE TITLE
Add 99Damage Demo Support

### ISSUE THREAD

**Issue by Topchris18** [akiver/cs-demo-manager#379]
Can you pls add 99Damage demo Support.
The analyse is almost right, but the rounds after the match is won count towards the normal rounds. The Problem is that the server needs 60 sec to change the map to the next one and those rounds change the stats

**Comment by akiver** [comment]
I didn't find any links to download demos from 99Damage on their website (I'm not German).  
Could you send me some demos from 99Damage?  
It could be supported unless it requires to write a new "demos analyzer"

**Comment by Topchris18** [comment]
Unfortunately I couldn't upload the files to github directly because they're bigger than 10MB but here's a google drive link to them.

https://drive.google.com/drive/folders/11azdavq7gfeoxsjdfdSYP2e-7X0JofaI?usp=sharing

They are all the first map on this server. The second map demos are always correct and no problems ocurred. 

If you need more demos feel free to ask.

**Comment by akiver** [comment]
Thank you, I will look into it but I can't promise anything.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
