### ISSUE TITLE
Exclude Scrimmage matches from statistics?

### ISSUE THREAD

**Issue by dinsdalepiranha** [akiver/cs-demo-manager#401]
Valve's (relatively) new Scrimmage matchmaking results in demos where you, your team, and/or your opponents are very likely not playing seriously.  A way to exclude these demos from your stats in CSGO Demos Manager would be useful.

**Comment by mBr001** [comment]
The program is no longer maintained by the dev, we might need to do the changes ourselves :(, hopefully whoever makes any changes uploads it to github as well.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
