### ISSUE TITLE
BUG - Rounds not being counted

### ISSUE THREAD

**Issue by lilgandhi1199** [akiver/cs-demo-manager#404]
This has actually been happening for awhile but I haven't bothered to complain about it. I think that not every round is being logged because in this game for example it ended 16:8 = 24 rounds and yet every single player shows "round_count": 23

I attached the game to this thread and linked my google drink link just incase. I'm sure I could find more examples if you want. I have 200+ demo files right now ready to be updated if you fix this bug.
Thanks

https://drive.google.com/file/d/1cqOwvcxyHI8w_KVCGJzPXPVnMxC6qtlV/view?usp=sharing

**Comment by lilgandhi1199** [comment]
Here give me a minute and I'll supply some more examples too.

**Comment by lilgandhi1199** [comment]
Ok I guess I only found one more in all those samples but there does tend to be a lot of lowered round counts all the time and I wonder if people left the game and rejoined a single round later all those times...or if it's something that can happen to any player randomly?

>>>and these are perhaps just examples of where it ended up happening randomly but to every single player at the same time!

So here's a game that ended 16:14 which is all 30 rounds filled and it says every player was only round_count = 29 or less
https://drive.google.com/open?id=1ZNKfQZes5fuOOggY3TVuRiZBGYenyTQg

**Comment by tehDrew** [comment]
is it counting from 0 perhaps?

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
