### ISSUE TITLE
Handling rounds when missing round start event occurs.

### ISSUE THREAD

**Issue by k4b4l74** [akiver/cs-demo-manager#419]
Hi, in the first demo ex-genuine-vs-pc419-m1-vertigo.dem here: https://www.hltv.org/matches/2338953/ex-genuine-vs-pc419-iem-katowice-2020-oceania-closed-qualifier with the good demo Parser (ESEA but same stuff with Valve), one round is missing (the true 9th round) and we have "two consecutive pistol rounds" 

![image](https://user-images.githubusercontent.com/724108/72465597-c15fd180-37d7-11ea-89d5-48b30a8e8ad8.png)

This because, round officially end and round start are not triggered for the end of 8th round and the start of the 9th round (see after tick 118xxx):

![image](https://user-images.githubusercontent.com/724108/72465637-d472a180-37d7-11ea-9e02-02ff2a5c64af.png)

I guess if we have "two consecutives" Round End Event in a Queue that store "Round Start / Round End / Round Officially Event ", maybe can end CurrentRound with Previous Round End Event tick + (5sec * Ticks) And we can Start a new Round.

That's will be probably a fix, dunno how many demos are in this case.

**Comment by k4b4l74** [comment]
I have started to modify DemoAnalyzer.
Because i have a modified version of DemoAnalyzer, i will not be able to commit my files (and it's not finished !!), i will need to clone the rep and do a PR when it will work (i hope if will not crash others demos....)
but you can see the work in progress by searching all LDLC-419 in this file: https://pastebin.com/rsQ5YUrx

It detect the bug and close and start new round correcly. But there is tons of stuffs left to do by removing and "recalculating" stuff from the "currentRound" that has twice rounds information.

![image](https://user-images.githubusercontent.com/724108/72511289-36b8ba00-384b-11ea-8572-3a0c08af885a.png)

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
