### ISSUE TITLE
Parsing private server demos

### ISSUE THREAD

**Issue by LouisAsanaka** [akiver/cs-demo-manager#473]
I understand that these demos recorded by `tv_record` or `tv_autorecord` aren't supported, but it seems like it isn't that hard to implement support for them. For my `tv_autorecord` demos, the analysis counts all the rounds correctly, but due to some sort of bug in CS:GO, some parts of the next game are also written into the demo file. This means that the `begin_new_match` event is called multiple times (within demoinfo). 

I managed to use the snippet from [here](https://github.com/saul/demofile/blob/master/src/entities/gamerules.ts#L36-L46) to compare the "phase" of the round, and see if the phase suddenly transitions from second-half to first-half, which would set a "game ended" flag that allows the rest of the handlers to ignore any new events. It worked, but I implemented it in an odd way that I'm not sure would be approved.

Is this something that can be implemented as like a work-around for buggy CS:GO code?

**Comment by akiver** [comment]
Could you send an affected demo?
If the server uses the default CSGO recording system and doesn't alter the game state (round restart, switch sides...) it should be fine even on a private server.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
