### ISSUE TITLE
Can't analyze one demo

### ISSUE THREAD

**Issue by TheRealAstroboy** [akiver/cs-demo-manager#486]
![image](https://user-images.githubusercontent.com/35332009/101697058-65e5a480-3a77-11eb-9e30-052bcdef9056.png)
demo code : CSGO-uFJrT-T9hwO-GZtWv-4Xmym-aD57M

**Comment by TheRealAstroboy** [comment]
json export
[match730_003452180490017046532_0644087070_195.dem.json.txt](https://github.com/akiver/CSGO-Demos-Manager/files/5669154/match730_003452180490017046532_0644087070_195.dem.json.txt)

**Comment by akiver** [comment]
Could you send the .dem file, not the JSON export (the share code is expired)?

**Comment by Xiguinilster** [comment]
how is it repaired?

**Comment by TheRealAstroboy** [comment]
> 
> 
> Could you send the .dem file, not the JSON export (the share code is expired)?

done !
http://dl.free.fr/mXwhEpRwZ

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
