### ISSUE TITLE
[3 Suggestions] Enhance Suspect list

### ISSUE THREAD

**Issue by diiigle** [akiver/cs-demo-manager#497]
I recently started using the `Suspect` list to track the (many) people I encounter hacking. And I had a few ideas how to improve the list:

- [ ]  Record the **timestamp** when the player was added to the list (related to #332)
  - from that you could also calculate the time till he was banned.
- [ ]  Record metadata such as:
   - type (AIM, WH, BH)
   - if encountered in public / MM / or Broken Fang Premier
   - custom comments (as with demos)
- [ ]  Automatically crawl suspects from your recent reports [steamcommunity.com/my/profile/gcpd/730/?tab=playerreports](https://steamcommunity.com/my/profile/gcpd/730/?tab=playerreports)

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
