### ISSUE TITLE
[PostGameStatistics] 14 out of 1200 buggy games

### ISSUE THREAD

**Issue by lilgandhi1199** [akiver/cs-demo-manager#501]
If you would like to look through these demos to patch up all your bugs...I've uploaded them to my google drive and included the json exports too. 

Before this last patch I actually had 20 broken games but looks like 6 more passed this time as I re-ran all my stats! Pretty cool!
If you'd like to finish them all off, I just am providing you this rare opportunity I think.

They flag as "bugged" every-time I parse through the exported jsons based on the following criteria:
            If ALL the player round counts are off by 1 or more from the total round scores (12:16) for example and everyone has 29 played rounds. This happens most often due to a simple surrender which tallys 1 higher so I left those in the first folder because they really don't mean anything. Perhaps they aren't getting caught as surrenders when they were. Not sure.
           But...the sub-folder "BAD" just has classicly wrong round counts and I'm not sure what rounds are missing or why but you could investigate if you wanted.

https://drive.google.com/file/d/1zNojT6X3_FaJZUD64p28JJhXT-EdvyVa/view?usp=sharing

**Comment by lilgandhi1199** [comment]
One last request if you could have jsons save the sharecodes instead of or next to ID...
I wonder if that super long ID is actually what I need to use your boiler program to re-generate the sharecode automagically?

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
