### ISSUE TITLE
Kills and Deaths don't add up (caused by team kills and Bombkills)

### ISSUE THREAD

**Issue by Daxelinho** [akiver/cs-demo-manager#506]
If you add up all the kills on the Rounds-Page of a specific player they don't add up to be the same as on the overview page. A team kill is counted as a normal kill so it differs by two. A new column with team kills/friendly fire could fix this.

A similar problem exists for deaths caused by the bomb exploding. They are included in the "deaths" column in the round overview. But the game seems to ignore them, therefore the count differs by one.

I have a demo I can provide you with if you wish where both of these things happen to one player in a game.

**Comment by SuperArwenAntoinette** [comment]
I checked on the issue of the bomb exploding and the deaths column, it seems to be correct from what I see.
I downloaded the match between the Navi and Team Liquid [here](https://www.hltv.org/matches/2346583/liquid-vs-natus-vincere-iem-katowice-2021) and on round 19, stewie2k tried to defuse the bomb and failed.

Hi stats on the deaths column seems fine from the overview and when I counted the rounds.
![image](https://user-images.githubusercontent.com/43733736/108728089-31589380-7564-11eb-89c7-567c7ce09794.png)

![image](https://user-images.githubusercontent.com/43733736/108728431-8bf1ef80-7564-11eb-90a1-fd89103fbb6a.png)

**Comment by Daxelinho** [comment]
That's indeed curious. Maybe it has something to do with the way the demo was "built"?
I was initially referring to this match/demo:

In this match I killed a teammate and died by the bomb.

![Demo Viewer1](https://user-images.githubusercontent.com/78887799/108734727-08b6a680-7530-11eb-8192-e70defdfdfac.png)
![Demo Viewer2](https://user-images.githubusercontent.com/78887799/108734747-0b190080-7530-11eb-9f7a-06933f2b2172.png)

**Comment by SuperArwenAntoinette** [comment]
From what I understand, team kills would deduct your kills right? 19 on the rounds while only 17 on the summary.
The deaths by bomb, I don't know about that.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
