### ISSUE TITLE
[Feedback] Export as XLS no death column, Win/Lost/Draw column, and Rounds for/against

### ISSUE THREAD

**Issue by Daxelinho** [akiver/cs-demo-manager#531]
Hi,

I often use the "Export as XLS" function, specifically a single file for a specific account.

But in the "General" tab there are columns for Kills and Assists but not for Deaths.
In addition to that, if it were possible, it would be great to add a column for Rounds for and against and maybe one for the outcome (Win, Lost or Draw) of the game from the exported players POV. #

**Comment by 3vaLpwner** [comment]
> 
> 
> Hi,
> 
> I often use the "Export as XLS" function, specifically a single file for a specific account.
> 
> But in the "General" tab there are columns for Kills and Assists but not for Deaths.
> In addition to that, if it were possible, it would be great to add a column for Rounds for and against and maybe one for the outcome (Win, Lost or Draw) of the game from the exported players POV. #
Kills on General equals Deaths, don't you think? Deaths are usable only for Players list

**Comment by 3vaLpwner** [comment]
> 
> 
> Hi,
> 
> I often use the "Export as XLS" function, specifically a single file for a specific account.
> 
> But in the "General" tab there are columns for Kills and Assists but not for Deaths.
> In addition to that, if it were possible, it would be great to add a column for Rounds for and against and maybe one for the outcome (Win, Lost or Draw) of the game from the exported players POV. #

https://github.com/Daxelinho

**Comment by Daxelinho** [comment]
No, what I mean is for single players.
I click on
> "Export as XLS"
> a message pops up with "You are going to export data for the player "xyz". Do you want to continue?" 
> Click on OK
> "Do you want to export data into a single file or multiple files?"
> Single

In the created file in the General tab the Kills and Assists are only of the player "xyz". Therefore deaths are not equal kills.
In fact, every stats is associated with the exported player "xyz". 5K, 4K, Trade Kill, ADR etc.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
