### ISSUE TITLE
XLS Export Request : Splitting Stats by Sides

### ISSUE THREAD

**Issue by chiefscott** [akiver/cs-demo-manager#542]
(Sorry if this isn't the right place to do this)

Requesting for a tab in the sheet of stats split by T / CT. 

Specifically if it were the same data set of the "Players" tab but Segmented by Terrorist or Counter-Terrorist.

Ideally there would be 3 Tabs, Both Sides Combined, T & CT.

Thank you!

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
