### ISSUE TITLE
Movie Making Resolution

### ISSUE THREAD

**Issue by StrPlayer** [akiver/cs-demo-manager#565]
Im having an issue changing it im trying to get 1080p but it gives me somthing around 1600p

**Comment by akiver** [comment]
The video resolution should match the game resolution, so if the game is started in 2560x1600, the video will be 2560x1600,
How/where do you change the game resolution?
Do you have any CSGO launch parameters set up?  (it could override video settings)

**Comment by StrPlayer** [comment]
No I use the resolution setting inside the movie making option

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
