### ISSUE TITLE
[ request ] add support for get5 demo

### ISSUE THREAD

**Issue by rpkaul** [akiver/cs-demo-manager#569]
since you are added eBot you should also add get5 support too, now almost everyone using get5 plugin to run csgo server , matches .
www.challengermode.com
5earena
almost everyone using this plugin  and 80% community servers also use get5 to run tournaments .
plugin link - https://github.com/splewis/get5

example in demo - https://cdn.discordapp.com/attachments/926310579004665897/1008272594979536976/unknown.png

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
