### ISSUE TITLE
ESL Meisterschaft demos get flagged as corrupted and cant be analyzed

### ISSUE THREAD

**Issue by uzhuzhh** [akiver/cs-demo-manager#579]
I tried to analyze our team's demos from matches of the ESL Meisterschaft. Demos are automatically created. They use their own eBot-tool in that league. Matches are always played best of 2 and I realized that it is always the first of the two maps that is flagged as corrupted.

FYI: sometimes you lose connection to the gameserver when they change maps after the first map.

**Comment by akiver** [comment]
Could you send a link to download the demos please?

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
