### ISSUE TITLE
Companion app for taking quick notes on a live game

### ISSUE THREAD

**Issue by ryefig** [akiver/cs-demo-manager#581]
I think there is a need in a companion app that will record gamestate of current game and you could "mark" some interesting moments on the timeline / game log that could be reviewed later from a demo.

**Comment by akiver** [comment]
I'm not sure to understand, do you mean to use the CSGO game state integration feature?

> you could "mark" some interesting moments on the timeline / game log

When and where? During a game?

**Comment by ryefig** [comment]
> I'm not sure to understand, do you mean to use the CSGO game state integration feature?
> 
> > you could "mark" some interesting moments on the timeline / game log
> 
> When and where? During a game?

Yes, during a game. For example, I go out and die from a one-way smoke. I alt-tab to find my death in the live feed of the game and make a note to learn how to throw this one-way after the game when I get the demo. Or I'm anchoring site and die from a really good flash so I would take a note to not forget to learn it afterwards

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
