### ISSUE TITLE
Translation: ru-Russian

### ISSUE THREAD

**Issue by Moondarker** [akiver/cs-demo-manager#597]
Hey, I'd like to work on translation for CIS countries :)
Already forked and working in background
Current progress: 177/1150 translation units

**Comment by NoPlagiarism** [comment]
@Moondarker Is there any progress?

**Comment by 3vaLpwner** [comment]
Holy cow, this guy is lost completely. Gonna help.

**Comment by Moondarker** [comment]
Yeah, I've been buried in work, sorry guys. You wanna take over, @NoPlagiarism @3vaLpwner?

**Comment by NoPlagiarism** [comment]
@Moondarker I guess, can you publish your translation branch?

**Comment by 3vaLpwner** [comment]
I'm on it, will publish my branch in 2 days on Friday.

**Comment by 3vaLpwner** [comment]
A little delay due to some external factors. Will be done tomorrow.

**Comment by 3vaLpwner** [comment]
Fnished:
https://github.com/3vaLpwner/CSGO-Demos-Manager
Whole fork is used for translation purposes only.
Need to be build and tested. Requesting @Moondarker and @NoPlagiarism to contact with me via TG: @Dr3vaL and discuss further improvements. I'll be available tomorrow for the whole day.

**Comment by NoPlagiarism** [comment]
Why don't create Pull Request and leave it draft for while. It will be created anyway, and also others can find out some errors, typos and test it

About TG... I've got ban on my account, so can only write to mutuals. 3 days left [Люблю телегу]

**Comment by 3vaLpwner** [comment]
Done:
https://github.com/akiver/CSGO-Demos-Manager/pull/617

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
