### ISSUE TITLE
Start money column for short matches wrong

### ISSUE THREAD

**Issue by Krohmium** [akiver/cs-demo-manager#604]
When analyzing short matches, the start money column of the 9th round is wrong.
Also, the round type is displayed as Force Buy instead of Pistol round.
![grafik](https://user-images.githubusercontent.com/17453037/211386260-b67ef09f-c8a3-4bd7-b636-bca857d9d488.png)

**Comment by akiver** [comment]
Could you please upload the demo?

**Comment by Krohmium** [comment]
CSGO-cLHh9-rePEr-Ew9mA-NKST6-PeS8N

**Comment by Krohmium** [comment]
https://we.tl/t-zDbepZOMFX
is the .dem File of a match with the same issue

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
