### ISSUE TITLE
demo cannot be analyzed

### ISSUE THREAD

**Issue by ueffel** [akiver/cs-demo-manager#610]
![image](https://user-images.githubusercontent.com/2247384/222576425-2bd46793-c8b2-4962-a93d-97711103bd5d.png)

So here it is, it's a faceit demo: <https://demos-europe-west2.faceit-cdn.net/csgo/1-003565c8-f30a-4444-bf4d-c7530bec881a-1-1.dem.gz>

In case it's not available anymore, it's also here: <https://www.dropbox.com/s/g8icys5rc0pe2aw/1-003565c8-f30a-4444-bf4d-c7530bec881a-1-1.dem.gz?dl=0>

**Comment by paulo-erichsen** [comment]
I have 2 more faceit demos that failed maybe for different reasons than the above

## demo 1

- faceit matchroom - https://www.faceit.com/en/csgo/room/1-ecde7ade-fac7-4345-a3eb-5bf471342c7a
- google-drive-mirror - https://drive.google.com/file/d/1cAHshXEv6w92Q86VeJBhlyERhq-6hao1/view?usp=sharing
- csgostats.gg match - https://csgostats.gg/match/100010223
- leetify match - https://beta.leetify.com/app/match-details/9ac681c5-13dd-4b57-93a0-be355c74c33d/overview

## demo 2

- faceit matchroom - https://www.faceit.com/en/csgo/room/1-7639e18c-84a9-4b12-b16e-0bf32e5fda27
- google-drive-mirror - https://drive.google.com/file/d/1GFXh5rbfIpFXHPI8RUkQmIZvK9tq2fA6/view?usp=sharing
- csgostats.gg match - https://csgostats.gg/match/98885047
- leetify match - https://beta.leetify.com/app/match-details/7d67c2c9-b062-450b-9f3d-1cdc29b0ac8a/overview

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
