### ISSUE TITLE
ffmpeg settings for input/extra parameters are not saved

### ISSUE THREAD

**Issue by K-orne** [akiver/cs-demo-manager#613]
Hi,

I'd like to store additional parameters for ffmpeg in the movie generator.
Until I have a serious case of "holding it wrong", it doesn't seem like values I add to "Extra input parameters" or "Extra parameters" are saved through restarts of the application.

Would it be possible to store them, similar to how the video/audio encoder settings can be stored permanently?

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
