### ISSUE TITLE
Switch to conventional commits

### ISSUE THREAD

**Issue by NoPlagiarism** [akiver/cs-demo-manager#615]
I guess it's has quite the same structure as [AngularJS one](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)

Also their website has a lot of translations

[conventionalcommits.org](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
