### ISSUE TITLE
Personal stats in the main page

### ISSUE THREAD

**Issue by geekwiz** [akiver/cs-demo-manager#625]
I have a suggestion which I believe would be really helpful in terms of evaluating performance and that is to add our personal stats in the main page where we have the list of all the demos so that the user is able to evaluate his/her performance easily. Now in order to see the number of kills and deaths we have to click on each demo to get those info and for someone like me that has over 150 demos it would be a tough task to accomplish.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
