### ISSUE TITLE
Not all columns showing on main page

### ISSUE THREAD

**Issue by JanEricNitschke** [akiver/cs-demo-manager#626]
Not all of the columns that i select show up on the main page. The ones i am specifically interested in are the 1vX columns.

They do show up when i select a particular demo but i would like to see (and sort by) them on the main screen.

![1vXcolumns_main](https://github.com/akiver/CSGO-Demos-Manager/assets/47750513/728446be-0175-4b67-8ec8-117022f2306e)
![column_settings](https://github.com/akiver/CSGO-Demos-Manager/assets/47750513/a14b9f32-cdea-4a95-b292-9c4e6eff6085)

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
