### ISSUE TITLE
Allow selection of multiple accounts for the main page.

### ISSUE THREAD

**Issue by JanEricNitschke** [akiver/cs-demo-manager#627]
I have added multiple (of my own) accounts to the demo manager. Currently if i want to see my highest RWS games i have to go through each account one by one and sort the columns by RWS.

This takes a lot of time especially with the amount of demos i have stored.

If possible i would like to have a feature where i can select multiple (or all) of the accounts to contribute to the main page simultaneously.

Issues could occur if multiple accounts are present in the same demo (which is not the case for me). For that case the ideal scenario would be to allow one to rank the accounts so that if multiple are present always the highest ranked one is displayed. Although if it is easier it would also be possible to pick a random one (or by steamid or alphabetically) or skip the demo entirely when having multiple accounts selected.

**Comment by OhGodANoob** [comment]
There is a workaround you could try. If you only have your accounts added then you could use Show All. The other way is that you can put certain demos into different folders and then use the drop down to select let's say "Personal Demos" or whatever you name the folder. To find specific demo location you can right click any demo and hit browse.

**Comment by JanEricNitschke** [comment]
If i click "Show All" i can not even see my RWS or other player stats at all.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
