### ISSUE TITLE
 All the enemy killing weapons in the demo have turned into C4 bombs

### ISSUE THREAD

**Issue by ProphetSAMA** [akiver/cs-demo-manager#629]
As mentioned, my game ID used special characters, which caused me to change all the weapons I used to C4 when viewing data using CSGODemo Manager

![image](https://github.com/akiver/CSGO-Demos-Manager/assets/66639916/151f9967-71df-4364-8fc1-6d319a7f79f1)

**Comment by akiver** [comment]
Hi, could you upload the demo please?

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
