### ISSUE TITLE
[2.15] JSON Seconds occurence is being divided by newly noted framerate instead of tickrate

### ISSUE THREAD

**Issue by lilgandhi1199** [akiver/cs-demo-manager#635]
OLD
            "tick": 27857,
            "seconds": 435.880066
NEW
            "tick": 27857,
            "seconds": 217.8125

It was correct before when you divided ticks by "server_tickrate": to get seconds.
Now it looks like you are dividing by "frame_rate":

When playing the demo ingame we can see that this kill infact occurs at 435 seconds aka 7m15s
![image](https://github.com/akiver/CSGO-Demos-Manager/assets/33440559/cc6fbdd2-7139-4104-b467-26bc733c6c0f)

**Comment by lilgandhi1199** [comment]
Note also your kill counts dropped drastically. I just use WinMerge to filecompare your old json to your new ones every version.

"3k_count": 14,
"2k_count": 27,
"1k_count": 68,

"3k_count": 0,
"2k_count": 1,
"1k_count": 7,

Trade kills also shifted slightly.
And what scares me some is has_won_round has changed in a lot of places too

^^^ Hopefully that was an improvement and not a regression.
There has been a change in what the program thinks is the income on round 16

![image](https://github.com/akiver/CSGO-Demos-Manager/assets/33440559/80b0b1f3-1252-41e1-a9f9-8a630312ea2e)

![image](https://github.com/akiver/CSGO-Demos-Manager/assets/33440559/036c9de6-30b7-48b4-a4e8-3c59545f8d53)

**Comment by lilgandhi1199** [comment]
After adjusting for these differences I can only see that weapon names have changed in some instances (probably more accurate detection right?)

"USP-S" has changed to "P2000"
"M4A1-S" has changed to "M4A4"
MP5-SD to MP7
R8 Revolver to Desert Eagle...

**Comment by lilgandhi1199** [comment]
![image](https://github.com/akiver/CSGO-Demos-Manager/assets/33440559/debe2524-70b6-4e8d-b1dc-db4fb18bf0e5)
This looks like a huge (albiet trivial) oversight in tallying. Because it doesn't seem like these occurrences are actually missing in the log.

![image](https://github.com/akiver/CSGO-Demos-Manager/assets/33440559/7fae95ad-f1ef-4004-b607-18d0ee9615b8)
Or again they became more accurate. I can't tell

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
