### ISSUE TITLE
I am unable to view the replay

### ISSUE THREAD

**Issue by ProphetSAMA** [akiver/cs-demo-manager#636]
Using CSGO Demosmanager to view DEMO files, everything was normal a few months ago, but I suddenly couldn't view them recently
![image](https://github.com/akiver/CSGO-Demos-Manager/assets/66639916/70b4513c-94ca-4998-a096-fccf0509b6dc)
`2023/9/26 1:40: 索引超出了数组界限。
Type: System.IndexOutOfRangeException
StackTrace:
   在 DemoInfo.DP.Handler.PacketEntitesHandler.Apply(PacketEntities packetEntities, IBitStream reader, DemoParser parser)
   在 DemoInfo.PacketEntities.Parse(IBitStream bitstream, DemoParser parser)
   在 DemoInfo.DP.DemoPacketParser.ParsePacket(IBitStream bitstream, DemoParser demo)
   在 DemoInfo.DemoParser.ParseDemoPacket()
   在 DemoInfo.DemoParser.ParseTick()
   在 DemoInfo.DemoParser.ParseNextTick()
   在 DemoInfo.DemoParser.ParseToEnd(CancellationToken token)
   在 Services.Concrete.Analyzer.ValveAnalyzer.<>c__DisplayClass5_0.<AnalyzeDemoAsync>b__0()
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Services.Concrete.Analyzer.ValveAnalyzer.<AnalyzeDemoAsync>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Services.Concrete.DemosService.<AnalyzeDemo>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Manager.ViewModel.Demos.DemoDetailsViewModel.<<get_AnalyzeDemoCommand>b__127_0>d.MoveNext()
-----------------------------------`
[errors.log](https://github.com/akiver/CSGO-Demos-Manager/files/12718040/errors.log)

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
