### ISSUE TITLE
Can't see my CS2 demos

### ISSUE THREAD

**Issue by ureeck** [akiver/cs-demo-manager#637]
Does Manager support CS2 demos?

**Comment by BinaryChop** [comment]
as stated on his twitter, CS2 demos will work on V3, which is in active development. Valve needs to release the demo api / gotv stuff.  [https://twitter.com/CSGODemoManager/status/1689690361277394948](url)

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
