### ISSUE TITLE
Can it be used as a demo cutter?

### ISSUE THREAD

**Issue by couleurm** [akiver/cs-demo-manager#638]
Hey, I'm thinking about ditching recording my clips with OBS and cutting them with LosslessCut and switching over to rendering CS:GO demos, can cs-demo-manager be used as a way to have multiple start/end points to skip parts of demos we don't plan on using?

**Comment by akiver** [comment]
Hi, if you mean to cut `.dem` files there is no plan to add it.
The v3 allows to record multiple "sequences", it's maybe what you want to do?
