### ISSUE TITLE
[Linux] distro-agnostic over native packaging formats

### ISSUE THREAD

**Issue by gerelef** [akiver/cs-demo-manager#640]
### What problem is this solving
Currently, cs-demo-manager supports a limited amount of packaging formats, only deb currently, locking out other distributions e.g. Fedora, arch, etc, with good reason; supporting multiple packaging formats is time consuming and takes away from development, while adding friction to timely deployments.

### Proposed solution
Create a flatpak package on Flathub instead of any native system package per se; this would allow for the application to be deployed on any distribution that has postgresql & flatpak installed.
Also, I'm unsure if it's possible for this specific situation, but there might be a way to add a version of postgresql as a dependency.

### Describe alternatives you've considered
Snaps are a direct alternative to flatpaks, but most people don't use snaps outside of Ubuntu.
AppImages are an alternative that are widely accepted within the Linux community with GNU userland; even more so than flatpaks, I'd say, however that's a personal estimate from my experience. There's a chance supporting AppImages would be even less effort than a flatpak, however I'm not aware of the possible downsides.

### Notes
It's probably common knowledge, however flatpaks are not _required_ to be sandboxed as far as I know.

**Comment by guihkx** [comment]
I think Flatpak support might be trickier than AppImage support, and the latter offers a similar level of "distro-agnosticism"...

**Comment by gerelef** [comment]
I'd completely forgotten about AppImages, I'll add them to the proposal as well, as a valid alternative. Should I rename the issue to "Containerized package support instead of native packaging formats"?

**Comment by akiver** [comment]
The next and future releases will provide an `AppImage`.
Please understand there is no plan to add additional distro-agnostic formats (snap, flatpak...).
It's time-consuming, and given the few Linux users based on GitHub downloads it's not a priority.
🙏

**Comment by guihkx** [comment]
That's completely understandable.

An AppImage package should work just fine for most Linux users.

If you'd allow me to make a recommendation, please always build the AppImage on the oldest (yet supported) LTS version of Ubuntu.

That way, the AppImage becomes more likely to run without issues on new, and old systems alike.

At the time of writing this, that version would be 20.04, Focal Fossa.

Thank you very much for your continuous commitment to resolve Linux-specific issues, I really appreciate it!

**Comment by gerelef** [comment]
Well done! Closing this as it's resolved; it's been added as a build target. Thank you :)
