### ISSUE TITLE
Error when trying to create videos from CS2 matches

### ISSUE THREAD

**Issue by K-orne** [akiver/cs-demo-manager#654]
### Describe the bug

Trying to create a video export from a replay results in the following error and no replay being recorded:
```
Sun, 03 Dec 2023 12:14:18 GMT | LOG | server | WS:: game process socket disconnected 1006 { type: 'Buffer', data: [] }
Sun, 03 Dec 2023 12:14:28 GMT | ERROR | server | Error while generating videos
Sun, 03 Dec 2023 12:14:28 GMT | ERROR | server | Error: ENOENT: no such file or directory, scandir 'C:\program files (x86)\steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\csdm\movie'
Sun, 03 Dec 2023 12:14:28 GMT | LOG | renderer | WS:: message with name "videos-generation-error" received from server
Sun, 03 Dec 2023 12:14:39 GMT | LOG | server | WS:: renderer process socket disconnected 1001 { type: 'Buffer', data: [] }
```

### Steps to reproduce

Start application, select demo, go to video tab, create or autogenerate a sequence and record it, cs2 launches but stays in the main menu, the mentioned error appears in the UI as well as the log

### Expected behavior

Demo is recorded and converted to video

### How often does this bug happen?

Every time

### Environment information

Version: 3.0.1
OS: win32 x64 10.0.22631
Electron: 27.1.3
Chrome: 118.0.5993.159
Last database migrations:
v1 - 2023-12-03T12:39:02.663Z

**Comment by akiver** [comment]
Thanks for the report!
It will be fixed in the next version.

**Comment by K-orne** [comment]
Thanks for all the hard work :)

**Comment by K-orne** [comment]
I'm not sure if this is actually the same issue or potentially a different one but I'm still unable to get demo recording going:
Full logfile of 3.0.2 is attached at this post.
[csdm.log](https://github.com/akiver/cs-demo-manager/files/13611444/csdm.log)
