### ISSUE TITLE
[Linux] Follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by guihkx** [akiver/cs-demo-manager#655]
### What problem is this solving

Right now, CSDM saves its data files in `~/.csdm`, not following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

### Proposed solution

To retain backward compatibility, we should first check if `~/.csdm` exists and just use that if it does.

Otherwise, I propose migrating to the following paths (old, new):

- `~/.csdm/settings.json` -> `$XDG_CONFIG_HOME/cs-demo-manager/settings.json`
- `~/.csdm/logs/` -> `$XDG_STATE_HOME/cs-demo-manager/logs/`
- `~/.csdm/tables/` -> `$XDG_STATE_HOME/cs-demo-manager/tables/`

**Comment by akiver** [comment]
Hi, the next version will follow the spec and there will be no backward compatibility.

- `XDG_CONFIG_HOME` is set and not empty -> `$XDG_CONFIG_HOME/.csdm`
- `XDG_CONFIG_HOME` is either not set or empty -> `$HOME/.config/.csdm`

Linux users can safely delete the old `$HOME/.csdm` folder - there will be a note about it in the changelog.

Thanks

**Comment by guihkx** [comment]
Thank you very much for working on this, @akiver.

However, I must say that having nested dot folders is not a thing that most programs do on Linux.

May I ask why not simply make it `~/.config/csdm` instead of `~/.config/.csdm`?

Thanks.

**Comment by akiver** [comment]
👍 it will be `~/.config/csdm`
