### ISSUE TITLE
Watch Player option

### ISSUE THREAD

**Issue by ar1a** [akiver/cs-demo-manager#666]
### What problem is this solving

I'd love for there to be a "Watch Player" option, like in v2. Skipping deaths/freezetime.

### Proposed solution

Reimplement #346

**Comment by ar1a** [comment]
legend, thanks for implementing that so fast

**Comment by hpksoldati** [comment]
If the player stays alive, when he advances to the next round the hud time counter becomes buggy in several situations.


Thank you also for this update!
