### ISSUE TITLE
Need to reconfigure database connection configuration after upgrade

### ISSUE THREAD

**Issue by lupohan44** [akiver/cs-demo-manager#671]
### What problem is this solving

Need to reconfigure database connection configuration after upgrade

### Proposed solution

Not need to reconfigure database connection configuration after upgrade

**Comment by akiver** [comment]
What do you mean by "reconfigure"?

The settings should be preserved, they are stored in `~/.csdm` and the last upgrade didn't change any settings.

**Comment by lupohan44** [comment]
![image](https://github.com/akiver/cs-demo-manager/assets/23133361/032882a0-9feb-46c1-9c14-1c2f211940f6)
After installation/upgrade, it require me to input all db related configuration again
The config shown in UI is incorrect, from port to username to password

**Comment by akiver** [comment]
Settings were removed during updates.  
Unfortunately it should happen again when upgrading from 3.0.1 to 3.0.2 but will not happen again after that.

Thank you!
