### ISSUE TITLE
Unable to Start Demo

### ISSUE THREAD

**Issue by Programatic** [akiver/cs-demo-manager#672]
### Describe the bug

When I attempt to watch a demo, I keep getting the notification that an error has occurred. 

### Steps to reproduce

1. Start Application
2. Analyze The Demo
3. Try to Watch Demo

### Expected behavior

I expected the demo to be launched is CS

### How often does this bug happen?

Every time

### Log file

Wed, 06 Dec 2023 04:25:21 GMT | ERROR | server | An error occurred while starting the game
Wed, 06 Dec 2023 04:28:20 GMT | LOG | server | WS:: message with name fetch-player-stats and uuid e6034aec-50ab-411d-8550-0053a0d89507 received from renderer process
Wed, 06 Dec 2023 04:28:53 GMT | LOG | server | WS:: message with name fetch-player-stats and uuid ff8bfca8-827e-4442-85a4-c9fd4650a725 received from renderer process
Wed, 06 Dec 2023 04:28:59 GMT | LOG | server | WS:: message with name is-cs-running and uuid 01f7b4f0-1561-47eb-b013-b2eeb0fcc0e3 received from renderer process
Wed, 06 Dec 2023 04:28:59 GMT | LOG | server | WS:: message with name watch-demo and uuid e5ec4d85-8fd2-41f9-80eb-15e8bae89d70 received from renderer process
Wed, 06 Dec 2023 04:29:00 GMT | LOG | server | Starting game with command "D:\program files (x86)\steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe" -insecure -novid -netconport 2121 +playdemo "D:\Users\ford\CS Demos\Pro Demos\1-030ee9c3-58c2-48d8-a32b-29cc800aa000-1-1.dem"  -width 1024 -height 768 -sw
Wed, 06 Dec 2023 04:29:00 GMT | LOG | renderer | WS:: message with name "starting-game" received from server
Wed, 06 Dec 2023 04:29:00 GMT | LOG | server | Game process exited with code 1
Wed, 06 Dec 2023 04:29:00 GMT | LOG | server | Game output: 
 Access is denied.

Wed, 06 Dec 2023 04:29:00 GMT | ERROR | server | An error occurred while starting the game
Wed, 06 Dec 2023 04:29:13 GMT | LOG | server | WS:: message with name is-cs-running and uuid 8f86567a-2ebe-4942-9a33-0cffb9b68f36 received from renderer process
Wed, 06 Dec 2023 04:29:14 GMT | LOG | server | WS:: message with name watch-demo and uuid 9c5dbb76-580c-4701-babd-bb2bc3600b9b received from renderer process
Wed, 06 Dec 2023 04:29:14 GMT | LOG | server | Starting game with command "D:\program files (x86)\steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe" -insecure -novid -netconport 2121 +playdemo "D:\Users\ford\CS Demos\Pro Demos\1-030ee9c3-58c2-48d8-a32b-29cc800aa000-1-1.dem"  -width 1024 -height 768 -sw
Wed, 06 Dec 2023 04:29:14 GMT | LOG | renderer | WS:: message with name "starting-game" received from server
Wed, 06 Dec 2023 04:29:14 GMT | LOG | server | Game process exited with code 1
Wed, 06 Dec 2023 04:29:14 GMT | ERROR | server | An error occurred while starting the game
Wed, 06 Dec 2023 04:29:14 GMT | LOG | server | Game output: 
 Access is denied.

Wed, 06 Dec 2023 04:32:06 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid 9ee097a0-2325-43e0-a3e4-eb4c2febff97 received from renderer process

### Environment information

- Verions 3.0.1
- Windows 11

**Comment by Programatic** [comment]
I will add, this does persist between reboots

**Comment by ar1a** [comment]
I had this problem because I had faceit ac open. closing it made it work

**Comment by akiver** [comment]
As @ar1a said the "Access denied" exception is due to the faceit AC.
I added a mention about this [here](https://cs-demo-manager.com/docs/faq/playback#cs2-demo-playback-doesnt-start-or-crashes ).
In the next version, the application will show a notification with a link to the doc when the game crashes
