### ISSUE TITLE
Video generation not following selected player.

### ISSUE THREAD

**Issue by Codiee1337** [akiver/cs-demo-manager#685]
### Describe the bug

Hello there. I'm trying to generate video with CS Demo Manager, but no matter what I tried, it doesn't wanna follow the selected player in the demo.

### Steps to reproduce

![image](https://github.com/akiver/cs-demo-manager/assets/33905082/6f853e1a-d12c-464b-8948-9aa45a105697)
![image](https://github.com/akiver/cs-demo-manager/assets/33905082/6e3b25f4-95ac-40d8-80d1-720ed110f9b0)

### Expected behavior

When the demo starts recording, it should follow the player. But currently, its randomly selects a player at the start of the round just like it would when you watch a demo.

### How often does this bug happen?

None

### Environment information

Version: 3.0.2
OS: win32 x64 10.0.22621
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-05T20:00:33.258Z

**Comment by akiver** [comment]
Do you keep the CS2 window focused as mentioned here https://cs-demo-manager.com/docs/cs2#video-generation?
If yes but it doesn't work please send the demo so I can try to reproduce the issue.
