### ISSUE TITLE
CS executable not found

### ISSUE THREAD

**Issue by dekhu48** [akiver/cs-demo-manager#689]
### Describe the bug

Watch demo doesnt work
watch at tickrate doent work
watch round doesnt work

### Steps to reproduce

Start cs demo manager
setup demo folder
analyze a demo
click on watch

### Expected behavior

expect the demo to play inside cs

### How often does this bug happen?

Every time

### Log file

Fri, 08 Dec 2023 13:21:28 GMT | LOG | server | WS:: message with name is-cs-running and uuid 0df7c099-e732-4860-bff6-a4a458123bbc received from renderer process
Fri, 08 Dec 2023 13:21:29 GMT | LOG | server | WS:: message with name watch-demo and uuid e99027fb-67db-4d60-829d-89edf3663211 received from renderer process
Fri, 08 Dec 2023 13:21:41 GMT | LOG | server | WS:: renderer process socket disconnected 1001 { type: 'Buffer', data: [] }
Fri, 08 Dec 2023 13:21:45 GMT | LOG | server | WS:: renderer process socket connected
Fri, 08 Dec 2023 13:21:45 GMT | LOG | renderer | WS:: connecting to server
Fri, 08 Dec 2023 13:21:45 GMT | LOG | renderer | WS:: connected
Fri, 08 Dec 2023 13:21:45 GMT | LOG | server | WS:: message with name connect-database and uuid a9cd57e3-b49a-450c-9182-c4da6ad2b164 received from renderer process
Fri, 08 Dec 2023 13:21:45 GMT | LOG | server | WS:: message with name init-application and uuid a3911f42-ad11-4402-8a13-06df7ce4457e received from renderer process
Fri, 08 Dec 2023 13:21:45 GMT | LOG | server | WS:: message with name fetch-matches-table and uuid ccf25ce8-d825-4eb8-aef8-ac7037d9dd96 received from renderer process
Fri, 08 Dec 2023 13:21:48 GMT | LOG | server | WS:: message with name fetch-match-by-checksum and uuid 7e47e6c9-abde-42bf-9728-2cf558c8a231 received from renderer process
Fri, 08 Dec 2023 13:21:50 GMT | LOG | server | WS:: message with name is-cs-running and uuid a45b953d-b0c3-4396-a4ee-d4868483add2 received from renderer process
Fri, 08 Dec 2023 13:21:50 GMT | LOG | server | WS:: message with name watch-demo and uuid 9467cd93-e5ea-404d-9cc8-cc954fc73ec5 received from renderer process
Fri, 08 Dec 2023 13:22:12 GMT | LOG | server | WS:: message with name is-cs-running and uuid c29d599c-e04c-44c8-bd66-434761eafcce received from renderer process
Fri, 08 Dec 2023 13:22:12 GMT | LOG | server | WS:: message with name watch-demo and uuid 7efe4ec5-0df6-45c9-ac2c-e8bd4cf4dc95 received from renderer process

### Environment information

Version: 3.0.2
OS: win32 x64 10.0.19045
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-02T23:34:01.972Z

**Comment by akiver** [comment]
Probably https://cs-demo-manager.com/docs/faq/playback#counter-strike-executable-not-found?

**Comment by dekhu48** [comment]
yup that fixed it 

maybe we should add a way to locate and select the executable if it's not found. 

if it's too much work let it be its not that big of deal anyways

thank u for your work
