### ISSUE TITLE
insertion of Demo error

### ISSUE THREAD

**Issue by pananniyanjie** [akiver/cs-demo-manager#691]
### Describe the bug

When I tried to import the demo from the community server, I encountered the following error message

`

### Demo links

`Command failed: psql -c "\copy rounds(number,start_tick,start_frame,freeze_time_end_tick,freeze_time_end_frame,end_tick,end_frame,end_officially_tick,end_officially_frame,team_a_name,team_b_name,team_a_score,team_b_score,team_a_side,team_b_side,team_a_start_money,team_b_start_money,team_a_equipment_value,team_b_equipment_value,team_a_money_spent,team_b_money_spent,team_a_economy_type,team_b_economy_type,duration,end_reason,winner_name,winner_side,overtime_number,match_checksum) FROM 'C:\Users\22818\AppData\Local\Temp\cs-demo-manager\2023-12-08_23-57-49_8_de_vertigo_G2_vs_Navi_rounds.csv' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
错误:  null value in column "winner_name" of relation "rounds" violates not-null constraint
����:  失败, 行包含(110, e455f0729ce3191c, 21, 132942, 138279, 134094, 139428, 0, 0, 0, 0, G2, Navi, 12, 9, 2, 3, 26550, 21200, 8800, 1000, 0, 0, semi, eco, 0, 0, null, 0, 0).
����:  COPY rounds, line 21: "21,132942,138279,134094,139428,0,0,0,0,G2,Navi,12,9,2,3,26550,21200,8800,1000,0,0,semi,eco,0,0,,0,0,..."

### Steps to reproduce

1.Select folder
2.select demo file
3.analysis demo
4. found error

### Expected behavior

success but i can‘t analysis my demo

### How often does this bug happen?

Every time

### Environment information

windows 11 x64

**Comment by akiver** [comment]
Could you please upload the demo?
It should be done in the "Demo links" template section.

**Comment by akiver** [comment]
@TResult97 This demo is corrupted - it stops in the middle of a round, the duration/round timeline is missing, and it doesn't contain the messages that a noncorrupted demo should have at the end.

Your demo:
![timeline](https://github.com/akiver/cs-demo-manager/assets/1842524/48999ebd-6f9a-43f7-bc75-7741169d289f)

Regular demo:
![timelineok](https://github.com/akiver/cs-demo-manager/assets/1842524/a6509b28-1b1f-4890-9c80-1a06ade1a19f)

The next version will show a better error message to diagnose this issue that is not fixable.
