### ISSUE TITLE
Support for demos from FASTCUP.NET

### ISSUE THREAD

**Issue by maxpain** [akiver/cs-demo-manager#707]
Hello. I'm the lead developer of [FASTCUP.net](https://fastcup.net)
How can we help to implement support for demo analyzing from our platform?

**Comment by akiver** [comment]
Hi, some questions that would help:

1. How do you record demos? (built-in match system, eBot, plugin...)
2. Is it the same system for CSGO and CS2?
3. Are there knife rounds?
4. Are there overtimes?
5. Are bots enabled?
6. What game modes/match lengths are supported?
7. I would need a bunch of CSGO/CS2 demos and if possible, links to the match page

Thank you

**Comment by etojuice** [comment]
1. With plugin.
2. Demo recording will begin at match start, or at beginning of knife round, if there is one. The only difference is that in CS2 our plugin utilizes `tv_record_immediate 1` setting.
3. Depends on type of map being played. For example, knife round is skipped on "aim_" maps.
4. Yes.
5. Depends on match settings.
6. Classic Competitive and Wingman. Any given match length is supported.
7. 
CS2 Competitive - https://cs2.fastcup.net/matches/11851975
CS2 Competitive (aim map) - https://cs2.fastcup.net/matches/11853992
CS2 Wingman - https://cs2.fastcup.net/matches/11826768

CS:GO Competitive - https://csgo.fastcup.net/matches/11853539
CS:GO Competitive (aim map) - https://csgo.fastcup.net/matches/11851962
CS:GO Wingman - https://csgo.fastcup.net/matches/11853408

**Comment by akiver** [comment]
Fastcup demos are now supported as v31.0 - thank you for the details.

**Comment by maxpain** [comment]
@akiver Thank you!
