### ISSUE TITLE
Windows Defender - Demo Analyse

### ISSUE THREAD

**Issue by hpksoldati** [akiver/cs-demo-manager#710]
### Describe the bug

It is not possible to load demo analyses.

Window Defender is blocking with this activity:
![image](https://github.com/akiver/cs-demo-manager/assets/16945944/f39fe8ef-d8e7-4585-ad3d-e1a94c03e998)

This program exhibits potentially unwanted behavior

Detected: PUA:Win32/Puwaders.C!ml
Status: Removed
A threat or app has been removed from this device
Affected items: file: C:\Users\hpk\AppData\Local\Programs\cs-demo-manager\resources\static\csda.exe

### Demo links

Most recent one: https://www.hltv.org/matches/2368606/virtuspro-vs-apeks-esl-challenger-atlanta-2023

### Steps to reproduce

1. Open demo with 2 clicks
2. Press analyse button

### Expected behavior

Show the screen with the demo stats

### How often does this bug happen?

None

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/13698607/csdm.log)

### Environment information

Win10

**Comment by akiver** [comment]
You will have to allow csda.exe from Windows Defender.
It has been [noticed](https://github.com/akiver/cs-demo-analyzer/issues/4) that Windows Defender may flag the analyzer program as a trojan.
Make sure your Defender definitions are up-to-date - I submitted the program and the last definitions don't flag it as a trojan - see this [issue](https://github.com/akiver/cs-demo-analyzer/issues/4).
