### ISSUE TITLE
Perfect world cs2 demo cannot be analyzed

### ISSUE THREAD

**Issue by sean8610** [akiver/cs-demo-manager#713]
### Describe the bug

Perfect world demo cannot be analyzed
![image](https://github.com/akiver/cs-demo-manager/assets/29730190/0275f714-02ec-4ed9-bc9d-d309e4570584)

![image](https://github.com/akiver/cs-demo-manager/assets/29730190/42936eb1-5205-4be7-9378-890e2f020e8a)

### Steps to reproduce

1download demo from perfect world pvp platform
2unzip the demo 
3open demo manager and select the location of the demo
4can not analyzed

### Expected behavior

can analyze pefect world pvp platform demo

### How often does this bug happen?

None

### Environment information

cs-demo-manager 3.0.6
windows11
cs2

**Comment by S18866877015** [comment]
我在网上搜的他们都说把数据源换成esl就可以分析了，我也是尝试了确实可以分析了，但是我一观看录像就会闪退到游戏主界面，你可以先改成esl的源尝试一下。
