### ISSUE TITLE
slow motion replay

### ISSUE THREAD

**Issue by S18866877015** [akiver/cs-demo-manager#716]
### Describe the bug

When I select a specific player kill view to watch the video, it always plays in slow motion for the kill.All playbacks on my computer have this problem

### Steps to reproduce

This issue occurs on all player-specific kill replays on my computer.

### Expected behavior

I would like to know how I can avoid this problem on my computer.

### How often does this bug happen?

Every time

### Log file

I'm sorry I don't know how to go about pulling the log file and that it doesn't report an error when that happens.

### Environment information

Version: 3.0.7
OS: win32 x64 10.0.19045
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-20T09:15:53.378Z

### Additional context

Sorry this is not a very standardized question, and please forgive me.

**Comment by OldGodShen** [comment]
If using the video generation function, then this is normal, and after transcoding, it will become a normal video

**Comment by akiver** [comment]
Do you mean the game is playing the demo in slow motion or the actual output video file is slower than it should be?
Please provide the demo and more information like for https://github.com/akiver/cs-demo-manager/issues/712, it will help.

**Comment by S18866877015** [comment]
Slow motion in video generation, I've learned that this is normal, problem solved, thanks for the reply!

**Comment by S18866877015** [comment]
> If using the video generation function, then this is normal, and after transcoding, it will become a normal video
Understood, thanks for the reply!
