### ISSUE TITLE
Steam Not Running

### ISSUE THREAD

**Issue by OldGodShen** [akiver/cs-demo-manager#717]
### Describe the bug

![image](https://github.com/akiver/cs-demo-manager/assets/57306382/7f7dfcfb-e00f-4139-b4a1-2c059caaa342)

### Demo links

Prompt for Steam Not Running When Checking Player's Exciting Fragments,but Steam is running.

### Steps to reproduce

1.Start CSDM
2.Open demo
3.Select player
4.Open highlights
5.Prompt for Steam Not Running When Checking Player's Exciting Fragments

### Expected behavior

I didn't encounter this situation on Windows 11 when I originally used it, but I did on this Windows 10

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/13760048/csdm.log)

### Environment information

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2023/‎12/‎23
操作系统内部版本	19045.3803
体验	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by akiver** [comment]
This error on Windows means that the process `steam.exe` is not running.
Could you check if the output of the Windows command `tasklist` contains `steam.exe` please?

**Comment by OldGodShen** [comment]
![image](https://github.com/akiver/cs-demo-manager/assets/57306382/f0ab6460-ef75-442e-83c0-b79feccb91ac)

**Comment by OldGodShen** [comment]
I don't have the command "tasklist" ?
![image](https://github.com/akiver/cs-demo-manager/assets/57306382/e21723ad-eecf-4264-9520-070ee057ddd5)

**Comment by OldGodShen** [comment]
I found the problem
I am missing the environment variable for %SystemRoot%\System32

**Comment by Muffiej** [comment]
I wonder if you can show the way to set  environment, still confuse about it, thx.

**Comment by akiver** [comment]
https://www.wikihow.com/Change-the-PATH-Environment-Variable-on-Windows
