### ISSUE TITLE
Player Names Not Showing Up

### ISSUE THREAD

**Issue by RyanBlakeIT** [akiver/cs-demo-manager#720]
### Describe the bug

After analyzing demo files, it still just shows "Player 1" "Player 2" etc.
![image](https://github.com/akiver/cs-demo-manager/assets/61893906/d9c6ebd0-12d2-4f73-9b12-6fc714e7cd31)
In the past it showed the actual player names.

### Steps to reproduce

1. Launch the application
2. Go to DEM section
3. Double click on an analyzed demo
4. You will see just "Player X" instead of their names.

### Expected behavior

I would expect to see the actual player names but instead see a generic Player name.

### How often does this bug happen?

None

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/13762586/csdm.log)

### Environment information

Version: 3.0.7
OS: win32 x64 10.0.19045
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-04T03:19:31.924Z

**Comment by akiver** [comment]
I added a doc about this potential issue [here](https://cs-demo-manager.com/docs/faq/stats#players-names-are-player-1-player-2-etc-and-avatars-are-missing) - let me know if it needs clarification.

As an improvement, the next version will have more API keys and will not request the Steam API every time you go to the demo's details page of a Valve demo (The app already tries to reduce API calls).
I would still recommend [generating your Steam API key](https://cs-demo-manager.com/docs/guides/settings#using-a-custom-steam-api-key) to avoid this issue.
