### ISSUE TITLE
Wrong kill display.

### ISSUE THREAD

**Issue by oevery** [akiver/cs-demo-manager#721]
### Describe the bug

Some kill are incorrectly displayed as C4, such as usp-s and nova.

### Steps to reproduce

![image](https://github.com/akiver/cs-demo-manager/assets/26798347/1a58a211-ea60-4a4f-ac35-04e6d2807bef)
![image](https://github.com/akiver/cs-demo-manager/assets/26798347/76a9af77-7324-41b5-908e-59b0e73aedee)

### Expected behavior

Correct display information.

### How often does this bug happen?

None

### Environment information

Version: 3.0.7
OS: win32 x64 10.0.22631
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-23T01:17:32.807Z

**Comment by akiver** [comment]
Please upload the demo.

**Comment by oevery** [comment]
<https://1drv.ms/u/s!AopKOQDJkrLMgaE7r0NNsoqvWXk9HA?e=iSMOM9> this is demo zip link, thanks a lot for this work.

**Comment by akiver** [comment]
This is a CS2 bug - there is a [workaround](https://github.com/markus-wa/demoinfocs-golang/pull/490) but the fix may not be accepted as it's a CS2 issue.
