### ISSUE TITLE
A China 5E Platform Demo Reported Error When Analyzing 

### ISSUE THREAD

**Issue by TheSorry404** [akiver/cs-demo-manager#725]
### Describe the bug

Analyze a Demo but it ran not correctly.
The Demo is from a China Platform called 5E, changed its source to ESL to analyze in app.

### Demo links

https://drive.google.com/file/d/1vZitXu3CJ4JaxGrNhSktpN_MzlkX4UnP/view?usp=sharing

### Steps to reproduce

1. Start the app
2. Choose the demo, change the source to ESL (Wanmei and 5E Platforms in China often can be analyzed in this source)
3. Analyze, then it goes wrong.

### Expected behavior

analyzed demo expected, but it goes to error.

### How often does this bug happen?

Every time

### Log file

Grenade nil in decoy start event
property 'm_unCurrentEquipmentValue' not found
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x11553c0, 0xc001dac4d0})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x11553c0?, 0xc001dac4d0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x11553c0?, 0xc001dac4c0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x10eba60?, 0xc001dac4b0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).PropertyValueMust(0xa?, {0x1218f3f, 0x19})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:163 +0x134
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.getUInt64(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/common/entity_util.go:18
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.(*Player).EquipmentValueCurrent(0xc000812ea0)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/common/player.go:432 +0x129
github.com/akiver/cs-demo-analyzer/pkg/api.(*PlayerEconomy).updateValues(0xc001be2870, 0xc00009b860?, 0xc000812ea0)
	github.com/akiver/cs-demo-analyzer/pkg/api/player_economy.go:43 +0x33
github.com/akiver/cs-demo-analyzer/pkg/api.(*Analyzer).computePlayersEconomies(0xc0000ba960)
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:550 +0xe5
github.com/akiver/cs-demo-analyzer/pkg/api.(*Analyzer).registerCommonHandlers.func9({})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:662 +0x3c
reflect.Value.call({0x10ee060?, 0xc000042f60?, 0xc0000a4090?}, {0x120fabe, 0x4}, {0xc0004516d0, 0x1, 0xc00070caf0?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x10ee060?, 0xc000042f60?, 0xc000456090?}, {0xc0004516d0?, 0xc6000000010443b8?, 0x0?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x10ee060?, 0xc000042f60?, 0x0?}, {0xc0004516d0?, 0x0?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000b2600, {0x1125320, 0x17035e0})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleFrameParsed(0xc00009b860, 0x0)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:527 +0x38
reflect.Value.call({0x10ef420?, 0xc000042e60?, 0xc001389e28?}, {0x120fabe, 0x4}, {0xc000451ef8, 0x1, 0x11edf60?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x10ef420?, 0xc000042e60?, 0x58?}, {0xc000451ef8?, 0x5b0000c00009bd01?, 0x1?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x10ef420?, 0xc000042e60?, 0xc00006b400?}, {0xc000451ef8?, 0xd770a6?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000b25a0, {0x10da800, 0x17035e0})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000b25b8?, {0x10da800?, 0x17035e0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000b25a0, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

### Environment information

Version: 3.0.5
OS: win32 x64 10.0.22621
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-07T13:43:06.185Z

### Additional context

I tried to read whats wrong wrote in the log but i cant LMAO

**Comment by TheSorry404** [comment]
I wanna know if theres a problem with this demo occured the app ran wrong, or theres truely a bug in this repo.
Thanks again for help!

**Comment by akiver** [comment]
Will be fixed with https://github.com/markus-wa/demoinfocs-golang/pull/489 adn https://github.com/markus-wa/demoinfocs-golang/pull/491
