### ISSUE TITLE
Add a option to export database

### ISSUE THREAD

**Issue by dekhu48** [akiver/cs-demo-manager#729]
### What problem is this solving

demos that are already analyzed can be exported without the use of CLI without reanalyzing them.

### Proposed solution

as the title suggests adda a option to export database in xlxs or any other format u prefer (csv)

### Describe alternatives you've considered

not applicable

**Comment by akiver** [comment]
You can already export matches from the list:

![2024-01-07 at 10 24 29](https://github.com/akiver/cs-demo-manager/assets/1842524/3f69f609-28b1-4a88-9b23-03a141cf03b3)

Is it what you are looking for?

**Comment by dekhu48** [comment]
oh my bad i analyzed the demo then deleted them 
the data is there in database but the option isnt available for me since i deleted the demos

**Comment by dekhu48** [comment]
Hey my bad it seems the export option is still there in the matches section

It seems in the excitedment of export/import feature in "Database" section that i overlooked those
my bad

it would still be cool if you could export the entire database in one click and even import a database that has been exported previously

If you dont like the idea let me know I'll close the issue 
thanks for your hard work

**Comment by akiver** [comment]
> I analyzed the demo then deleted them

It's recommended to keep demos somewhere - new analysis features or bug fixes require to re-analyze demos.

I added a [documentation](https://cs-demo-manager.com/docs/guides/database#exporting-the-database) to export/import the database.

Thanks
