### ISSUE TITLE
Invalid byte sequence for encoding UTF8

### ISSUE THREAD

**Issue by JareCoder** [akiver/cs-demo-manager#735]
### Describe the bug

Demo analysis fails due to invalid byte sequence for encoding UTF8.

### Demo links

https://drive.google.com/file/d/1sCuYFFnD6gWA0VNPnO-bBlAnMvVX_cdi/view?usp=sharing

### Steps to reproduce

1. Download demo
2. Try to analyze
3. Fails

### Expected behavior

1. Download demo
2. Try to analyze
3. Demo gets analyzed and added to the DB

### How often does this bug happen?

Sometimes

### Log file

{unknown event "player_activate" 0}
{unknown event "player_activate" 0}
Command failed: psql -c "\copy matches(checksum,game,demo_path,name,date,source,type,map_name,server_name,client_name,tick_count,tickrate,framerate,duration,network_protocol,build_number,game_type,game_mode,game_mode_str,is_ranked,kill_count,assist_count,death_count,shot_count,winner_name,winner_side,overtime_count,max_rounds,has_vac_live_ban) FROM 'C:\Users\jesse\AppData\Local\Temp\cs-demo-manager\64_xelectro-esports-inceptor-lrtsy_de_nuke_match.csv' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
ERROR:  invalid byte sequence for encoding "UTF8": 0xf6 0x72 0x74 0x73
CONTEXT:  COPY matches, line 1

Error: Command failed: psql -c "\copy matches(checksum,game,demo_path,name,date,source,type,map_name,server_name,client_name,tick_count,tickrate,framerate,duration,network_protocol,build_number,game_type,game_mode,game_mode_str,is_ranked,kill_count,assist_count,death_count,shot_count,winner_name,winner_side,overtime_count,max_rounds,has_vac_live_ban) FROM 'C:\Users\jesse\AppData\Local\Temp\cs-demo-manager\64_xelectro-esports-inceptor-lrtsy_de_nuke_match.csv' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
ERROR:  invalid byte sequence for encoding "UTF8": 0xf6 0x72 0x74 0x73
CONTEXT:  COPY matches, line 1

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:303:5)

### Environment information

Version: 3.1.0
OS: win32 x64 10.0.19045
Electron: 28.1.0
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2023-12-11T16:05:19.302Z

### Additional context

Downloaded a bunch of tournament demos from our Google Drive. A little over half of them analyzed with no issues, but 9 demos failed due to the same error. An example out of these 9 has been provided with logs.

**Comment by akiver** [comment]
Fixed in v3.2.0 - please note that you will have to clear the demos cache from the database [optimization menu](https://cs-demo-manager.com/docs/guides/database#optimizing-the-database) before analyzing the demo; otherwise, you will have a "Match not found" error.
