### ISSUE TITLE
2D Viewer, Sound loud

### ISSUE THREAD

**Issue by H1ghSyst3m** [akiver/cs-demo-manager#737]
### Describe the bug

The Sound in the Viewer is absurd loud, and it's like I am hearing a year 2000 sound 

### Steps to reproduce

1. Open a Match
2. Open the 2D Viewer
3. Hear the sound of kills

### Expected behavior

A more clean and a bit quieter, so that doesn't destroy the ear drum

### How often does this bug happen?

Every time

### Environment information

Version: v3.1.0
OS: Windows 11

**Comment by akiver** [comment]
You can mute/change the volume level from the playback bar.

![c](https://github.com/akiver/cs-demo-manager/assets/1842524/a1953cb4-0a79-4ada-b466-632a7660e795)

The sounds are from CS but I may remove this feature or add filtering settings in the future - not sure yet.
