### ISSUE TITLE
when watch highlights and lowlights the camera is not on the right player

### ISSUE THREAD

**Issue by ChengHeEric** [akiver/cs-demo-manager#745]
### Describe the bug

when watch highlights and lowlights the camera is not on the right player

### Steps to reproduce

1. start 
2. analyse match
3. watch a player's highlights

### Expected behavior

i would expect watch the selected player's camera, but i see other players' camera 

### How often does this bug happen?

None

### Environment information

Version: 3.2.0
OS: win32 x64 10.0.22631
Electron: 28.1.1
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2023-12-06T12:14:16.490Z

**Comment by mini337** [comment]
also have this problem

**Comment by akiver** [comment]
did you see the [doc](https://cs-demo-manager.com/docs/faq/playback#the-camera-doesnt-focus-on-the-player)?

**Comment by ChengHeEric** [comment]
yes, I saw the doc, but the method in the doc only works when you want to watch highlights, it doesn't work when you want to watch lowlights.

**Comment by akiver** [comment]
The v3.3.0 uses the new CS2 command `spec_lock_to_accountid` - it should solve this kind of issue.
