### ISSUE TITLE
Demo from Blast Premier is not recognized 

### ISSUE THREAD

**Issue by dekhu48** [akiver/cs-demo-manager#747]
### Describe the bug

The managers fails to recognize demos from blast premiere 
I have to manually set the source of Demos to Faceit to analyze them  

### Demo links

https://www.hltv.org/matches/2368867/astralis-vs-vitality-blast-premier-spring-groups-2024
Let me know if you want the demos uploaded to gdrive 

### Steps to reproduce

load the demos in manager.

the manager doesn't recognize the source of demo, so there is nothing to do further  

### Expected behavior

cs demo manager should recognize the demos from blast tournament 

### How often does this bug happen?

None

### Environment information

Version: 3.2.0
OS: win32 x64 10.0.19045
Electron: 28.1.1
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2023-12-12T12:48:50.170Z

**Comment by akiver** [comment]
Do Blast events **ALWAYS** use the FaceIt tournament system?

**Comment by dekhu48** [comment]
yes, Most TO's use faceit these days

**Comment by OhGodANoob** [comment]
I downloaded these demos a few days ago and was just setting source to ESL and that also seemed to work
