### ISSUE TITLE
Utilize SQLite or another CLI database that doesn't require installation

### ISSUE THREAD

**Issue by henriquelbsouza** [akiver/cs-demo-manager#749]
### What problem is this solving

Avoid installation and background proccess of a database (can be heavy on low-end PCS) and people that are not really technical can use the software easily :)

### Proposed solution

Utilize SQLite (or any other local database that doesn't require installation) and bundle it with the installation :)

**Comment by akiver** [comment]
dup https://github.com/akiver/cs-demo-manager/discussions/741
