### ISSUE TITLE
Make default startup option as NO

### ISSUE THREAD

**Issue by osztenkurden** [akiver/cs-demo-manager#750]
### What problem is this solving

In my case, I couldn't configure Postgres for a few days. It meant that the demo manager started up every time, and wouldn't let me go into the settings, due to not existing PSQL binary, and I had to manually close it each time.

### Proposed solution

Make default startup option to "No" or allow access to settings without postgres, it's ridiculous.

**Comment by akiver** [comment]
You don't necessarily need to access the CS:DM settings (or any other app settings) to configure whether apps can automatically start when you log in.
You should use your OS settings to change it. On Windows, it's called `Startup Apps` and it's accessible from the settings.

**Comment by osztenkurden** [comment]
This is just a bad UX design. This is demo analyzer app, it has no business being launched with OS on startup by default, and having inaccessible settings if not properly configured. I shouldn't be forced either to install postgres (separate issue, I know), nor to go to OS Settings to disable auto launch. Slack has this option available from tray.
