### ISSUE TITLE
Support demos from MatchZy plugin

### ISSUE THREAD

**Issue by BigSaVo** [akiver/cs-demo-manager#751]
### What problem is this solving

Support demos from the [MatchZy](https://github.com/shobhit-pathak/MatchZy) plugin.

Demos:

- https://www.just1life-gaming.de/videos/2024-02-04_20-03-42_19_de_inferno_team_Reyshion_vs_team_FUCHS.dem

**Comment by akiver** [comment]
@BigSaVo I updated the issue as it's a feature request, not a bug.
Do you have more demos? Also, your demo's link seems broken.

**Comment by rpkaul** [comment]
Hello, I also wanted to add this plugin's matches to CSDM. This plugin is the replacement for Get5 for now. 
Here are the five demos that a few teams played today.
https://drive.usercontent.google.com/download?id=1UinXbc7PkxzxU64-WD4abQcEKn3pUxfn&export=download&authuser=0
https://drive.usercontent.google.com/download?id=1UiSPpDK7H-hRFS-J-e_WJ6ArMdamt6nH&export=download&authuser=0
https://drive.usercontent.google.com/download?id=1UqdzPwlWXT76wr8yhXWc0WQXc6z80qkU&export=download&authuser=0
https://drive.usercontent.google.com/download?id=1Up89cKE7fhbXiBIFfyPTLiG9dTK7ocX6&export=download&authuser=0
https://drive.usercontent.google.com/download?id=1UoR0PV4rLWskLPdg5EVc9BhqBOa3QVCP&export=download&authuser=0

**Comment by BigSaVo** [comment]
Hello, the link works for me and I can download the demo. I'll upload the demo to an external site. see if it works then. We have two demos. One on the map Vertigo runs without problems. Only the one with Inferne cannot be analyzed.

Even with the new version 3.3.0 the error remains

**Comment by BigSaVo** [comment]
The link is valid for 7 days

https://we.tl/t-qe5JZrXjZm

**Comment by ehwhattaugonnado** [comment]
I can supply any additional demos you need. demoinfocs-golang is able to handle them

**Comment by milkywayfarer** [comment]
We're using MatchZy to play all of our matches, and the only problem we encountered is that the knife round and warmup after it is all considered "the first round" along with the real play, but shows all the knife-warmup kills happening at 0:00. Everything else is successfully parsed and correctly displayed in 2D Viewer. I can always throw the example demo from the latest CS2 version your way, if you at me. We play every week.
