### ISSUE TITLE
Demo analysis error

### ISSUE THREAD

**Issue by lxr1994620** [akiver/cs-demo-manager#758]
### Describe the bug

分析demo失败

### Steps to reproduce

1.启动程序
2.右键点击demo分析

### Expected behavior

我本来以为可以分析成功，但提提示：分析录像时发生错误

### How often does this bug happen?

Every time

### Log file

runtime: VirtualAlloc of 32213835776 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x7d469b?, 0xca8e924000?})
	runtime/panic.go:1077 +0x65 fp=0xfded9ff728 sp=0xfded9ff6f8 pc=0x35ac65
runtime.sysUsedOS(0xc6c3404000, 0x780182000)
	runtime/mem_windows.go:83 +0x1bb fp=0xfded9ff788 sp=0xfded9ff728 pc=0x33a51b
runtime.sysUsed(...)
	runtime/mem.go:77
runtime.(*mheap).allocSpan(0xc898a0, 0x3c00c1, 0x0, 0xf8?)
	runtime/mheap.go:1351 +0x487 fp=0xfded9ff828 sp=0xfded9ff788 pc=0x34bc87
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:968 +0x5c fp=0xfded9ff870 sp=0xfded9ff828 pc=0x34b43c
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
	runtime/asm_amd64.s:509 +0x49 fp=0xfded9ff880 sp=0xfded9ff870 pc=0x386609

goroutine 19 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:474 +0x8 fp=0xc0008e5180 sp=0xc0008e5170 pc=0x3865a8
runtime.(*mheap).alloc(0xc000105040?, 0xc0008e51f8?, 0x0?)
	runtime/mheap.go:962 +0x5b fp=0xc0008e51c8 sp=0xc0008e5180 pc=0x34b39b
runtime.(*mcache).allocLarge(0xc242e0f3c8?, 0x7801801a0, 0x18?)
	runtime/mcache.go:234 +0x85 fp=0xc0008e5210 sp=0xc0008e51c8 pc=0x3393e5
runtime.mallocgc(0x7801801a0, 0x6d1b40, 0x1)
	runtime/malloc.go:1127 +0x4f6 fp=0xc0008e5278 sp=0xc0008e5210 pc=0x330596
runtime.makeslice(0xc0008e52c0?, 0xc241584000?, 0xc000a84030?)
	runtime/slice.go:103 +0x49 fp=0xc0008e52a0 sp=0xc0008e5278 pc=0x36dac9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*fieldState).set(0xc0008c7000?, 0xc0009dedb0, {0x6acce0?, 0xc242e55cdc})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/field_state.go:38 +0x9f fp=0xc0008e5310 sp=0xc0008e52a0 pc=0x5e561f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc0000b61c0, 0xc0002fbcb0?, 0xc0008e5608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:422 +0x12e fp=0xc0008e5450 sp=0xc0008e5310 pc=0x5dfa0e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc000164aa0, 0xc000374680)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618 fp=0xc0008e5720 sp=0xc0008e5450 pc=0x5e0178
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.sendTableParser.OnPacketEntities-fm(0x1?)
	<autogenerated>:1 +0x2b fp=0xc0008e5740 sp=0xc0008e5720 pc=0x61e1eb
runtime.call16(0xc000598c30, 0xc000118828, 0x0, 0x0, 0x0, 0x8, 0xc0008e5c90)
	runtime/asm_amd64.s:747 +0x48 fp=0xc0008e5760 sp=0xc0008e5740 pc=0x386ae8
runtime.reflectcall(0x7aee40?, 0xc000374680?, 0x1?, 0x7d6f11?, 0x0?, 0x12?, 0x7aee40?)
	<autogenerated>:1 +0x36 fp=0xc0008e57a0 sp=0xc0008e5760 pc=0x38d496
reflect.Value.call({0x6c61a0?, 0xc000118828?, 0xc0008e5e28?}, {0x7d169c, 0x4}, {0xc0008e5ef8, 0x1, 0x7afb40?})
	reflect/value.go:596 +0xce7 fp=0xc0008e5db0 sp=0xc0008e57a0 pc=0x3eaa67
reflect.Value.Call({0x6c61a0?, 0xc000118828?, 0x58?}, {0xc0008e5ef8?, 0x8b0000c000105001?, 0x1?})
	reflect/value.go:380 +0xb9 fp=0xc0008e5e28 sp=0xc0008e5db0 pc=0x3e9b39
github.com/markus-wa/godispatch.callConsumerCode({0x6c61a0?, 0xc000118828?, 0x36bac5?}, {0xc0008e5ef8?, 0x3370a6?, 0x35d8ce?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f fp=0xc0008e5e78 sp=0xc0008e5e28 pc=0x5d9a7f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0001fe540, {0x7aee40, 0xc000374680})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4 fp=0xc0008e5f20 sp=0xc0008e5e78 pc=0x5d99d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0001fe558?, {0x7aee40?, 0xc000374680?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f fp=0xc0008e5f68 sp=0xc0008e5f20 pc=0x5da36f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0001fe540, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0 fp=0xc0008e5fc0 sp=0xc0008e5f68 pc=0x5da290
github.com/markus-wa/godispatch.(*Dispatcher).AddQueues.func2()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x25 fp=0xc0008e5fe0 sp=0xc0008e5fc0 pc=0x5da125
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0008e5fe8 sp=0xc0008e5fe0 pc=0x3885c1
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

goroutine 1 [semacquire]:
runtime.gopark(0x2?, 0xc242ecf040?, 0x40?, 0xe2?, 0x328b57?)
	runtime/proc.go:398 +0xce fp=0xc0008e92d8 sp=0xc0008e92b8 pc=0x35d8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.semacquire1(0xc0001fe560, 0x0?, 0x1, 0x0, 0x0?)
	runtime/sema.go:160 +0x229 fp=0xc0008e9340 sp=0xc0008e92d8 pc=0x36bd69
sync.runtime_Semacquire(0x5dac60?)
	runtime/sema.go:62 +0x25 fp=0xc0008e9378 sp=0xc0008e9340 pc=0x3844c5
sync.(*WaitGroup).Wait(0xc0001fe540?)
	sync/waitgroup.go:116 +0x48 fp=0xc0008e93a0 sp=0xc0008e9378 pc=0x395b48
github.com/markus-wa/godispatch.(*Dispatcher).sendToken(0xc0001fe540, {0xc00010c098?, 0xe372?, 0x381d00?}, {0x6acd60?, 0x83ca00?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:282 +0x11b fp=0xc0008e9430 sp=0xc0008e93a0 pc=0x5da97b
github.com/markus-wa/godispatch.(*Dispatcher).SyncQueues(...)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:240
github.com/markus-wa/godispatch.(*Dispatcher).SyncAllQueues(...)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:245
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleStringTables(0xc000104b60, 0xc242ee4140)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/stringtables.go:532 +0x53 fp=0xc0008e9508 sp=0xc0008e9430 pc=0x6144b3
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleFullPacket(0xc242ef0000?, 0xc242ee4100)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/s2_commands.go:361 +0x25 fp=0xc0008e9530 sp=0xc0008e9508 pc=0x610fa5
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc000104b60)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:380 +0x331 fp=0xc0008e9610 sp=0xc0008e9530 pc=0x60c811
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2-fm()
	<autogenerated>:1 +0x25 fp=0xc0008e9628 sp=0xc0008e9610 pc=0x61e0a5
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc000104b60)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146 fp=0xc0008e9780 sp=0xc0008e9628 pc=0x60b646
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc00014000b, 0x61}, {0x40?, {0xc00011a0f8?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:208 +0xb89 fp=0xc0008e9e38 sp=0xc0008e9780 pc=0x620569
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc00014000b?, 0x61?}, {0xc000142008, 0x39}, {0x0, {0xc00011a0f8, 0x6}, {0xc00011a0c8, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:252 +0x6c fp=0xc0008e9e70 sp=0xc0008e9e38 pc=0x620a0c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc000144010, 0x4, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb fp=0xc0008e9f18 sp=0xc0008e9e70 pc=0x669c5b
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45 fp=0xc0008e9f40 sp=0xc0008e9f18 pc=0x669e65
runtime.main()
	runtime/proc.go:267 +0x2b2 fp=0xc0008e9fe0 sp=0xc0008e9f40 pc=0x35d4b2
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0008e9fe8 sp=0xc0008e9fe0 pc=0x3885c1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000081fa8 sp=0xc000081f88 pc=0x35d8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.forcegchelper()
	runtime/proc.go:322 +0xb8 fp=0xc000081fe0 sp=0xc000081fa8 pc=0x35d758
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000081fe8 sp=0xc000081fe0 pc=0x3885c1
created by runtime.init.6 in goroutine 1
	runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000083f78 sp=0xc000083f58 pc=0x35d8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:321 +0xdf fp=0xc000083fc8 sp=0xc000083f78 pc=0x34819f
runtime.gcenable.func1()
	runtime/mgc.go:200 +0x25 fp=0xc000083fe0 sp=0xc000083fc8 pc=0x33d2e5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000083fe8 sp=0xc000083fe0 pc=0x3885c1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000038070?, 0x83aef0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000091f70 sp=0xc000091f50 pc=0x35d8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.(*scavengerState).park(0xc740e0)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc000091fa0 sp=0xc000091f70 pc=0x345a29
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:658 +0x59 fp=0xc000091fc8 sp=0xc000091fa0 pc=0x345fd9
runtime.gcenable.func2()
	runtime/mgc.go:201 +0x25 fp=0xc000091fe0 sp=0xc000091fc8 pc=0x33d285
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x3885c1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x400000?, 0x70?, 0x5e?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000085e20 sp=0xc000085e00 pc=0x35d8ce
runtime.runfinq()
	runtime/mfinal.go:193 +0x107 fp=0xc000085fe0 sp=0xc000085e20 pc=0x33c347
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000085fe8 sp=0xc000085fe0 pc=0x3885c1
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:163 +0x3d

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00048df50 sp=0xc00048df30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00048dfe0 sp=0xc00048df50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00048dfe8 sp=0xc00048dfe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 20 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00008ff50 sp=0xc00008ff30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00008ffe0 sp=0xc00008ff50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 21 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x1?, 0x8?, 0x75?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000489f50 sp=0xc000489f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000489fe0 sp=0xc000489f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000489fe8 sp=0xc000489fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 35 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00048ff50 sp=0xc00048ff30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00048ffe0 sp=0xc00048ff50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00048ffe8 sp=0xc00048ffe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 5 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000093f50 sp=0xc000093f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000093fe0 sp=0xc000093f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 36 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x1?, 0x8?, 0x75?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000495f50 sp=0xc000495f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000495fe0 sp=0xc000495f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000495fe8 sp=0xc000495fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 6 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000491f50 sp=0xc000491f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000491fe0 sp=0xc000491f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000491fe8 sp=0xc000491fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 37 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x30?, 0xdf?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000497f50 sp=0xc000497f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000497fe0 sp=0xc000497f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000497fe8 sp=0xc000497fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 38 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x30?, 0xdf?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00049ff50 sp=0xc00049ff30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00049ffe0 sp=0xc00049ff50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00049ffe8 sp=0xc00049ffe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 7 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x1?, 0x8?, 0x75?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000493f50 sp=0xc000493f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000493fe0 sp=0xc000493f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000493fe8 sp=0xc000493fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 22 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00048bf50 sp=0xc00048bf30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00048bfe0 sp=0xc00048bf50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00048bfe8 sp=0xc00048bfe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 39 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc0004a1f50 sp=0xc0004a1f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0004a1fe0 sp=0xc0004a1f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0004a1fe8 sp=0xc0004a1fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 23 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x14?, 0x24?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00049bf50 sp=0xc00049bf30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00049bfe0 sp=0xc00049bf50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00049bfe8 sp=0xc00049bfe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x1?, 0x74?, 0xc5?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc0000a1f50 sp=0xc0000a1f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0000a1fe0 sp=0xc0000a1f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a1fe8 sp=0xc0000a1fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 40 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00009df50 sp=0xc00009df30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00009dfe0 sp=0xc00009df50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00009dfe8 sp=0xc00009dfe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 24 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x30?, 0xdf?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00049df50 sp=0xc00049df30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00049dfe0 sp=0xc00049df50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00049dfe8 sp=0xc00049dfe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x1?, 0x8?, 0x75?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc0000a3f50 sp=0xc0000a3f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0000a3fe0 sp=0xc0000a3f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a3fe8 sp=0xc0000a3fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 10 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x30?, 0xdf?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc0000a9f50 sp=0xc0000a9f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0000a9fe0 sp=0xc0000a9f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a9fe8 sp=0xc0000a9fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 11 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc0000abf50 sp=0xc0000abf30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0000abfe0 sp=0xc0000abf50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

goroutine 25 [GC worker (idle)]:
runtime.gopark(0xcc8280?, 0x3?, 0x80?, 0x67?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc0000a5f50 sp=0xc0000a5f30 pc=0x35d8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc0000a5fe0 sp=0xc0000a5f50 pc=0x33eee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a5fe8 sp=0xc0000a5fe0 pc=0x3885c1
created by runtime.gcBgMarkStartWorkers in goroutine 19
	runtime/mgc.go:1219 +0x1c

### Environment information

版本:3.2.0
系统：win11

**Comment by artemmiz1** [comment]
The issue is being worked on and is acknowledged by the creator, stay tuned for updates
