### ISSUE TITLE
cs2 is updated , and can not lanuch cs2 to play demo now

### ISSUE THREAD

**Issue by Julian332** [akiver/cs-demo-manager#762]
### Describe the bug

cs2 is updated , and can not lanuch cs2 to play demo now

### Steps to reproduce

cs2 is updated , and can not lanuch cs2 to play demo now

### Expected behavior

lanuch cs2 to play demo

### How often does this bug happen?

None

### Environment information

version: 3.2.2
os: win11

**Comment by akiver** [comment]
fixed as of 3.2.3
