### ISSUE TITLE
An error while analyzing the demo. (Faceit Demo)

### ISSUE THREAD

**Issue by privateCS** [akiver/cs-demo-manager#766]
### Describe the bug

serializer CWorld: field path 14773952 has no field (14773952)
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x10468a0?, 0xc000aa2080})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x10468a0?, 0xc000aa2080?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0xfdcbe0?, 0xc000aa2070?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2._panicf(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/panicf.go:6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*serializer).getDecoderForFieldPath(0x0?, 0xc000527200, 0x143703a0eb8?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/serializer.go:46 +0xf9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc0007fe000, 0xc0002c9ce0?, 0xc0009db608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:419 +0xe6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc000098af0, 0xc00069c750)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618
reflect.Value.call({0xff61a0?, 0xc000008840?, 0xc0009dbe28?}, {0x110169c, 0x4}, {0xc0009dbef8, 0x1, 0x10dfb40?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0xff61a0?, 0xc000008840?, 0x58?}, {0xc0009dbef8?, 0x3a0000c00007bd01?, 0x4?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0xff61a0?, 0xc000008840?, 0xc9bac5?}, {0xc0009dbef8?, 0xc670a6?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000965a0, {0x10dee40, 0xc00069c750})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000965b8?, {0x10dee40?, 0xc00069c750?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000965a0, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

### Demo links

https://drive.google.com/file/d/1dTnm5D5f_OfllvjFYqsEBPGmDyYcG8R1/view?usp=sharing

### Steps to reproduce

1. open the CS Demo Manager
2. insert demo file into demo manager
3. Click the "Analyse" button

### Expected behavior

Analysing the demo

### How often does this bug happen?

Sometimes

### Log file

Sun, 18 Feb 2024 13:18:40 GMT | LOG | server | WS:: message with name fetch-matches-table and uuid fe34c73a-143f-4dec-b4a2-f3a13280433f received from renderer process
Sun, 18 Feb 2024 13:18:41 GMT | LOG | server | WS:: message with name fetch-demos-table and uuid 5177ebbe-44c1-44b5-9ab5-9987a73558de received from renderer process
Sun, 18 Feb 2024 13:18:41 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sun, 18 Feb 2024 13:18:41 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sun, 18 Feb 2024 13:18:41 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sun, 18 Feb 2024 13:18:41 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sun, 18 Feb 2024 13:18:41 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sun, 18 Feb 2024 13:18:41 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sun, 18 Feb 2024 13:18:57 GMT | LOG | server | WS:: message with name navigate-to-demo-or-match and uuid c8dc4b16-01ea-4f67-81dc-7ef261721f30 received from renderer process
Sun, 18 Feb 2024 13:18:57 GMT | LOG | server | WS:: message with name navigate-to-demo-or-match and uuid f8f44bac-59d4-45b8-851c-b1ee199d3565 received from renderer process
Sun, 18 Feb 2024 13:18:57 GMT | LOG | server | WS:: message with name load-demo-by-path and uuid 0c17d50b-6b6d-4b2e-81a5-a028c74f0e70 received from renderer process
Sun, 18 Feb 2024 13:18:57 GMT | LOG | renderer | WS:: message with name "navigate-to-demo" received from server
Sun, 18 Feb 2024 13:18:57 GMT | LOG | renderer | WS:: message with name "navigate-to-demo" received from server
Sun, 18 Feb 2024 13:18:59 GMT | LOG | server | WS:: message with name add-demos-to-analyses and uuid 3d082d61-7ddc-42d5-8e55-0d1e4c74f4d2 received from renderer process
Sun, 18 Feb 2024 13:18:59 GMT | LOG | renderer | WS:: message with name "demos-added-to-analyses" received from server
Sun, 18 Feb 2024 13:18:59 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 18 Feb 2024 13:18:59 GMT | LOG | server | starting demo analyzer with command "C:\Users\private\AppData\Local\Programs\cs-demo-manager\resources\static\csda.exe" -demo-path="C:\Users\private\Desktop\1-ae9c045c-a636-4116-999b-a5a0ff294100-1-1.dem" -output="C:\Users\private\AppData\Local\Temp\cs-demo-manager" -format="csdm" -source="faceit"
Sun, 18 Feb 2024 13:18:59 GMT | ERROR | server | serializer CWorld: field path 14773952 has no field (14773952)
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x10468a0?, 0xc000aa2080})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x10468a0?, 0xc000aa2080?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0xfdcbe0?, 0xc000aa2070?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2._panicf(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/panicf.go:6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*serializer).getDecoderForFieldPath(0x0?, 0xc000527200, 0x143703a0eb8?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/serializer.go:46 +0xf9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc0007fe000, 0xc0002c9ce0?, 0xc0009db608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:419 +0xe6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc000098af0, 0xc00069c750)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618
reflect.Value.call({0xff61a0?, 0xc000008840?, 0xc0009dbe28?}, {0x110169c, 0x4}, {0xc0009dbef8, 0x1, 0x10dfb40?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0xff61a0?, 0xc000008840?, 0x58?}, {0xc0009dbef8?, 0x3a0000c00007bd01?, 0x4?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0xff61a0?, 0xc000008840?, 0xc9bac5?}, {0xc0009dbef8?, 0xc670a6?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000965a0, {0x10dee40, 0xc00069c750})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000965b8?, {0x10dee40?, 0xc00069c750?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000965a0, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

Sun, 18 Feb 2024 13:18:59 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 18 Feb 2024 13:18:59 GMT | LOG | server | demo analyzer exited with code 1
Sun, 18 Feb 2024 13:18:59 GMT | ERROR | server | Error while analyzing demo
Sun, 18 Feb 2024 13:18:59 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 18 Feb 2024 13:19:04 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid fa28d8fc-d785-4761-b0db-d9f0082a536b received from renderer process

### Environment information

Version: 3.2.0
OS: win32 x64 10.0.22631
Electron: 28.1.1
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2023-12-26T17:12:39.615Z

**Comment by akiver** [comment]
Update the app to the latest version it will work

**Comment by privateCS** [comment]
ah, many thanks for your quick help. I didn't check for a new version as i have 'Auto-Update' enabled.
