### ISSUE TITLE
Detect and warn access denied exception

### ISSUE THREAD

**Issue by HrK3FTW** [akiver/cs-demo-manager#767]
### Describe the bug

When i try to play any demo it shows : 
Counter-Strike starting...
Then another popup show saying :
An error occurred

### Steps to reproduce

![Screenshot_33](https://github.com/akiver/cs-demo-manager/assets/160444371/4cbcaddc-60e2-4aaf-8ab5-b0dc59607b8b)

### Expected behavior

Before it was working and now it isnt

### How often does this bug happen?

None

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/14325406/csdm.log)

### Environment information

Version: 3.3.0
OS: win32 x64 10.0.19045
Electron: 28.2.3
Chrome: 120.0.6099.283
Last database migrations:
v1 - 2023-12-04T05:25:17.937Z

**Comment by akiver** [comment]
Close any anticheat software https://cs-demo-manager.com/docs/faq/playback#cs2-demo-playback-doesnt-start-or-crashes

**Comment by akiver** [comment]
The next version will detect and inform the user to close any anti-cheat software in such cases.
