### ISSUE TITLE
15-15 Draw is shown as a Defeat (Ver. 3.3.0)

### ISSUE THREAD

**Issue by Zombie150302** [akiver/cs-demo-manager#768]
### Describe the bug

On the download page a 15-15 draw is shown as a defeat and not a tie
![Bug_with_draw](https://github.com/akiver/cs-demo-manager/assets/157007476/b013d870-95f1-4021-a8d8-e71cea85c0bf)

### Steps to reproduce

1. Start App
2. Go to the download page
3. a 15-15 game should show up as a defeat

### Expected behavior

The Program should show it as a tie

### How often does this bug happen?

Every time

### Environment information

Version: 3.3.0
OS: win32 x64 10.0.22631
Electron: 28.2.3
Chrome: 120.0.6099.283
Last database migrations:
v1 - 2024-01-18T09:43:43.337Z

**Comment by akiver** [comment]
Could you please upload the file `matches.info`?
You can find it in the folder `C:\Users\USERNAME\.csdm`

**Comment by Zombie150302** [comment]
[matches.zip](https://github.com/akiver/cs-demo-manager/files/14336100/matches.zip)

**Comment by akiver** [comment]
Thx it will be fixed in the next release
