### ISSUE TITLE
Error whilst parsing FACEIT demo

### ISSUE THREAD

**Issue by KillaBoi** [akiver/cs-demo-manager#772]
### Describe the bug

An error occurs whilst attempting to analyse a FACEIT demo, the following popup shows up and it is advised to report here:

```
serializer CWorld: field path 10350272 has no field (10350272)
stacktrace:
goroutine 19 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x11c68a0?, 0xc000c56070})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x11c68a0?, 0xc000c56070?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x115cbe0?, 0xc000c56060?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2._panicf(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/panicf.go:6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*serializer).getDecoderForFieldPath(0x0?, 0xc000b16240, 0x1aa04660598?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/serializer.go:46 +0xf9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc000b0a000, 0xc0002f9cb0?, 0xc000491608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:419 +0xe6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc000160aa0, 0xc0007a5e10)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618
reflect.Value.call({0x11761a0?, 0xc000118828?, 0xc000491e28?}, {0x128169c, 0x4}, {0xc000491ef8, 0x1, 0x125fb40?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x11761a0?, 0xc000118828?, 0x58?}, {0xc000491ef8?, 0xc20000c000105001?, 0x6?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x11761a0?, 0xc000118828?, 0xe1bac5?}, {0xc000491ef8?, 0xde70a6?, 0xe0d8ce?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00024c540, {0x125ee40, 0xc0007a5e10})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc00024c558?, {0x125ee40?, 0xc0007a5e10?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00024c540, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a
```

### Demo links

https://www.faceit.com/en/cs2/room/1-96ac9172-3bc8-4457-a161-273be5013bd1

### Steps to reproduce

Download demo
Open Demo
Press Analyze button

### Expected behavior

I would expect it to analyze the match and display the stats and info as normal

### How often does this bug happen?

Every time

### Log file

Sun, 25 Feb 2024 03:28:50 GMT | LOG | server | WS:: message with name load-demo-by-path and uuid 647cd344-2be3-434d-a569-bb6ee6545ca6 received from renderer process
Sun, 25 Feb 2024 03:28:51 GMT | LOG | server | WS:: message with name add-demos-to-analyses and uuid 61e4fa2b-3b6d-438a-a833-2c6e4c18fde2 received from renderer process
Sun, 25 Feb 2024 03:28:51 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 25 Feb 2024 03:28:51 GMT | LOG | renderer | WS:: message with name "demos-added-to-analyses" received from server
Sun, 25 Feb 2024 03:28:51 GMT | LOG | server | starting demo analyzer with command "C:\Users\pc\AppData\Local\Programs\cs-demo-manager\resources\static\csda.exe" -demo-path="C:/Program Files (x86)/Steam/steamapps/common/Counter-Strike Global Offensive/game/csgo/replays/1-96ac9172-3bc8-4457-a161-273be5013bd1-1-1.dem" -output="C:\Users\pc\AppData\Local\Temp\cs-demo-manager" -format="csdm" -source="faceit" -positions="true"
Sun, 25 Feb 2024 03:28:51 GMT | ERROR | server | serializer CWorld: field path 10350272 has no field (10350272)
stacktrace:
goroutine 19 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x11c68a0?, 0xc000c56070})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x11c68a0?, 0xc000c56070?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x115cbe0?, 0xc000c56060?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2._panicf(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/panicf.go:6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*serializer).getDecoderForFieldPath(0x0?, 0xc000b16240, 0x1aa04660598?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/serializer.go:46 +0xf9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc000b0a000, 0xc0002f9cb0?, 0xc000491608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:419 +0xe6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc000160aa0, 0xc0007a5e10)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618
reflect.Value.call({0x11761a0?, 0xc000118828?, 0xc000491e28?}, {0x128169c, 0x4}, {0xc000491ef8, 0x1, 0x125fb40?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x11761a0?, 0xc000118828?, 0x58?}, {0xc000491ef8?, 0xc20000c000105001?, 0x6?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x11761a0?, 0xc000118828?, 0xe1bac5?}, {0xc000491ef8?, 0xde70a6?, 0xe0d8ce?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc00024c540, {0x125ee40, 0xc0007a5e10})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc00024c558?, {0x125ee40?, 0xc0007a5e10?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc00024c540, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

Sun, 25 Feb 2024 03:28:51 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 25 Feb 2024 03:28:51 GMT | LOG | server | demo analyzer exited with code 1
Sun, 25 Feb 2024 03:28:51 GMT | ERROR | server | Error while analyzing demo
Sun, 25 Feb 2024 03:28:51 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 25 Feb 2024 03:30:35 GMT | LOG | server | WS:: message with name navigate-to-demo-or-match and uuid ef8a23c2-c09d-4e46-98f5-650dfab60f17 received from renderer process
Sun, 25 Feb 2024 03:30:35 GMT | LOG | server | WS:: message with name load-demo-by-path and uuid cda53e8d-7459-41e0-ba74-0d7204df3cfc received from renderer process
Sun, 25 Feb 2024 03:30:35 GMT | LOG | renderer | WS:: message with name "navigate-to-demo" received from server
Sun, 25 Feb 2024 03:30:36 GMT | LOG | server | WS:: message with name add-demos-to-analyses and uuid 5b6c11fa-4124-4289-8e1b-c972fb444cf3 received from renderer process
Sun, 25 Feb 2024 03:30:36 GMT | LOG | renderer | WS:: message with name "demos-added-to-analyses" received from server
Sun, 25 Feb 2024 03:30:36 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 25 Feb 2024 03:30:36 GMT | LOG | server | starting demo analyzer with command "C:\Users\pc\AppData\Local\Programs\cs-demo-manager\resources\static\csda.exe" -demo-path="C:\Users\pc\AppData\Local\Temp\7zO4879C1D2\1-96ac9172-3bc8-4457-a161-273be5013bd1-1-1.dem" -output="C:\Users\pc\AppData\Local\Temp\cs-demo-manager" -format="csdm" -source="faceit" -positions="true"
Sun, 25 Feb 2024 03:30:36 GMT | ERROR | server | serializer CWorld: field path 10350272 has no field (10350272)
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x11c68a0?, 0xc0008ce080})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x11c68a0?, 0xc0008ce080?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x115cbe0?, 0xc0008ce070?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2._panicf(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/panicf.go:6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*serializer).getDecoderForFieldPath(0x0?, 0xc0009041b0, 0x29d13030a28?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/serializer.go:46 +0xf9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc0000bc000, 0xc0002b7ce0?, 0xc000b07608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:419 +0xe6
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc00008aaf0, 0xc00067d6c0)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618
reflect.Value.call({0x11761a0?, 0xc000008840?, 0xc0002b7890?}, {0x128169c, 0x4}, {0xc000b07ef8, 0x1, 0x3?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x11761a0?, 0xc000008840?, 0x0?}, {0xc000b07ef8?, 0x2d00000000000000?, 0x0?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x11761a0?, 0xc000008840?, 0xe1bac5?}, {0xc000b07ef8?, 0xde70a6?, 0xe0d8ce?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000885a0, {0x125ee40, 0xc00067d6c0})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000885b8?, {0x125ee40?, 0xc00067d6c0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000885a0, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

Sun, 25 Feb 2024 03:30:36 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 25 Feb 2024 03:30:36 GMT | LOG | server | demo analyzer exited with code 1
Sun, 25 Feb 2024 03:30:36 GMT | ERROR | server | Error while analyzing demo
Sun, 25 Feb 2024 03:30:36 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sun, 25 Feb 2024 03:32:45 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid ff1a241f-7fc6-4010-b702-473da8d58e89 received from renderer process

### Environment information

Version: 3.2.0
OS: win32 x64 10.0.19045
Electron: 28.1.1
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2024-01-12T21:18:57.670Z

**Comment by akiver** [comment]
Works fine with the latest version, please update the app
