### ISSUE TITLE
Keep getting "Access is denied." when trying to analyse demoes

### ISSUE THREAD

**Issue by thekennethlim** [akiver/cs-demo-manager#781]
### Describe the bug

I suddenly can't analyse demoes anymore. Every demo I try to analyse returns the error "Access is denied."

### Demo links

Here's an example match that I tried to analyse the demoes for: https://www.faceit.com/en/cs2/room/1-e062a9dc-08ca-4acd-95ff-95ce8897fa96

### Steps to reproduce

1. I refresh the demoes from my demo folder
2. I select the demoes I want to analyse
3. The demoes cannot be analysed and the error message is "Access is denied."

### Expected behavior

I used to be able to analyse demoes just fine. I really don't understand why it has stopped working properly.

### How often does this bug happen?

Every time

### Log file

Sat, 16 Mar 2024 15:23:29 GMT | LOG | server | WS:: message with name fetch-demos-table and uuid 5b691a65-dafc-4a3f-a84b-a55e44aa2095 received from renderer process
Sat, 16 Mar 2024 15:23:29 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sat, 16 Mar 2024 15:23:29 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sat, 16 Mar 2024 15:23:29 GMT | LOG | renderer | WS:: message with name "demos-to-fetch-progress" received from server
Sat, 16 Mar 2024 15:23:32 GMT | LOG | server | WS:: message with name add-demos-to-analyses and uuid 67238805-6aab-4214-a2d4-7df91226f985 received from renderer process
Sat, 16 Mar 2024 15:23:32 GMT | LOG | server | starting demo analyzer with command "C:\Users\kenne\AppData\Local\Programs\cs-demo-manager\resources\static\csda.exe" -demo-path="F:/FEMALECS/DEMOS/1-e062a9dc-08ca-4acd-95ff-95ce8897fa96-2-1.dem" -output="C:\Users\kenne\AppData\Local\Temp\cs-demo-manager" -format="csdm" -source="faceit"
Sat, 16 Mar 2024 15:23:32 GMT | LOG | renderer | WS:: message with name "demos-added-to-analyses" received from server
Sat, 16 Mar 2024 15:23:32 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 16 Mar 2024 15:23:32 GMT | ERROR | server | Access is denied.

Sat, 16 Mar 2024 15:23:32 GMT | LOG | server | demo analyzer exited with code 1
Sat, 16 Mar 2024 15:23:32 GMT | ERROR | server | Error while analyzing demo
Sat, 16 Mar 2024 15:23:32 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 16 Mar 2024 15:23:32 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 16 Mar 2024 15:23:37 GMT | LOG | server | starting demo analyzer with command "C:\Users\kenne\AppData\Local\Programs\cs-demo-manager\resources\static\csda.exe" -demo-path="F:/FEMALECS/DEMOS/1-e062a9dc-08ca-4acd-95ff-95ce8897fa96-1-1.dem" -output="C:\Users\kenne\AppData\Local\Temp\cs-demo-manager" -format="csdm" -source="faceit"
Sat, 16 Mar 2024 15:23:37 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 16 Mar 2024 15:23:37 GMT | ERROR | server | Access is denied.

Sat, 16 Mar 2024 15:23:37 GMT | LOG | server | demo analyzer exited with code 1
Sat, 16 Mar 2024 15:23:37 GMT | ERROR | server | Error while analyzing demo
Sat, 16 Mar 2024 15:23:37 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 16 Mar 2024 15:23:37 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 16 Mar 2024 15:23:45 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid 15d3f317-30e4-47a2-bcda-1065e9c6fe3c received from renderer process

### Environment information

Version: 3.3.2

OS: win32 x64 10.0.22631

Electron: 29.1.1

Chrome: 122.0.6261.111

Last database migrations:

v1 - 2023-12-05T00:35:12.660Z

**Comment by akiver** [comment]
It's probably because another process is locking the .dem file.
Make sure to close the game and any anti-cheat, you can find different solutions to find which [process is locking a file](https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows).
