### ISSUE TITLE
✨ Add a dropdown of available codecs

### ISSUE THREAD

**Issue by SivertGullbergHansen** [akiver/cs-demo-manager#783]
### What problem is this solving

# ❓ The problem in question:
For some users it might be overwhelming and rather problematic adjusting the ffmpeg parameters, to save disk space when compiling videos.

Right now it is rather difficult (requires advanced knowledge) to adjust the ffmpeg parameters, specifically the video and audio codecs. Codecs are reliant on compatible containers, and for the moment it seems the only output container is AVI, which does not support all modern codecs (specifically AV1). 

To the extent of my knowledge, it is also not possible (or rather very difficult) to define the container.

### Proposed solution

# ✨ Feature Request: Dropdowns for video- and audio codecs, and a dropdown to specify the container (file-type)

This provides users with little to no knowledge on ffmpeg the ability to save drive space by giving them simple pre-defined options.

Personally I would use AV1 codec and mp4 container for all my video files, however it is rather difficult to achieve this with the current setup. I know I can manually set the video and audio codecs, however not all codecs are compatible with AVI. Considering AV1 is only compatible with mp4 and MKV (to the extent of my knowledge), it would also be nice to add a dropdown for the output file type (which should dynamically update the dropdowns for video- and audio codecs compatible with the selected container).

### Describe alternatives you've considered

An alternative would be to not add any dropdowns and instead give the ability to change the ouput file name/container. At least then we can use all codecs available.

**Comment by akiver** [comment]
👋 
The next version will have a dropdown menu to select the container (`avi`, `mp4` or `mkv`).
I prefer to stick with a text input for codecs because it's for advanced users, and available codecs depend on the FFmpeg build (you can use a custom FFmpeg build from the app settings).
