### ISSUE TITLE
Historic Match History Download

### ISSUE THREAD

**Issue by TheOfficialDroid** [akiver/cs-demo-manager#807]
### What problem is this solving

The ability to download historic match demo's, outside of the current system that's available; Such as GCPD.

### Proposed solution

Valve provides "GCPD" to view historic match information and obtain demo's for those matches; A way to download via GCPD along with aligning the date of the match with the correct date provided on the page...

### Describe alternatives you've considered

Thus far I've manually downloaded matches and altered metadata to provide the correct date of the match; However this is extremely cumbersome and time consuming.. I'm aware of another project that /tries/ to automate this, however it doesn't seem to be maintained.

**Comment by akiver** [comment]
Hi!

Unfortunately, there is no API to fetch these data without being logged on Steam.
It means it can't be automated without asking for Steam credentials or copying/pasting Steam auth cookies.
I don't like both ideas, and the app will never ask for Steam credentials.

While it could be an external project idea, I don't plan to work on a tool that scraps data from the Steam page myself.
I didn't try it, but maybe this project would work as it seems to be recent https://github.com/claabs/cs-demo-downloader

I'm closing this issue as there is no actionable action.
That would be possible if the Steam GC ever exposes unranked/wingman matches.
