### ISSUE TITLE
can't focus on player in certain demo.

### ISSUE THREAD

**Issue by jaredliu2018** [akiver/cs-demo-manager#808]
### Describe the bug

can't focus on player when playback this demo. 

### Demo links

https://cdn.b5csgo.com.cn/highlights/cs2/highlight_1248463866_2419783372396645920_16.mp4

### Steps to reproduce

1. Start CSDM
2. Analyze demo with source of "Valve"
3. Watch player kill video (No matter which round, which player)

### Expected behavior

I would expected camera focus on the right player, but it doesn't. Camera seems focus on a strange place. 
After "1" or "space" key was pressed, it can be recovered. 

### How often does this bug happen?

Every time

### Environment information

- Version: 3.4.0
- OS: Windows 10

**Comment by akiver** [comment]
Probably related to https://github.com/akiver/cs-demo-manager/issues/775

Could you upload the demo? The link seems incorrect.

**Comment by jaredliu2018** [comment]
Can't upload demo file, it's too large.
update link：
https://cdn.b5csgo.com.cn/b5demo/demos/b5match_2419783372396645920.dem.zip

**Comment by akiver** [comment]
It will be fixed in the next release - it looks like the camera is stuck in free mode with some non-Valve demos.
