### ISSUE TITLE
Focus on wrong player in Highlights Replay.

### ISSUE THREAD

**Issue by NhanDotJS** [akiver/cs-demo-manager#812]
### Describe the bug

When watching highlights, it cuts to correct moments of kills. However the camera is focus on the first victim (viewing from enemy pov), it keeps on following him on into next moments, until he dies, then it switch to the killer (normal pov switching, not "highlight pov")
First spotted in a recent Demo after 26/4/24 update.
The bug existed in demos prior to 26/04/2024 CS2 Update, the demo is confirmed to be working perfectly before CS2DM v3.5.1

### Steps to reproduce

1. Start the app
2. Go to analyse a demo from 26/4/24 update using V3.5.1
3. Right click, watch highlights, enemy pov
4. As described above
5. Even when watch highlights in player pov, still showing the first victim as above, so on...

### Expected behavior

I would expect to see POV switching to victim in Highlight Moments, but I'm seeing a random POV in the highlights moment. (It cut to the correct highlight moment tho)

### How often does this bug happen?

None

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/15132482/csdm.log)

### Environment information

Version: 3.5.1
OS: win32 x64 10.0.22631
Electron: 30.0.1
Chrome: 124.0.6367.60
Last database migrations:
v2 - 2024-04-10T16:27:35.716Z
v1 - 2024-03-01T19:07:19.475Z

### Additional context

I do run my db from a local server, instead of on device. I don't think it related but should provide some context for some error in log file

**Comment by akiver** [comment]
Fixed in v3.5.2, it looks like the command `spec_lock_account_id` is now hidden, that's why the camera focus was not working.
