### ISSUE TITLE
Removal of spec_lock

### ISSUE THREAD

**Issue by ahmedchn** [akiver/cs-demo-manager#813]
### What problem is this solving

Hi! Hope you are doing great
Thanks for this amazing software. I would like to make a humble request. I learn and analyze a lot of utility from demos. From demo manager when i watch any segment of for example "flashbang" it locks into the particular player. I cannot change the camera for that. Please could you remove spec_lock "account id"  i would be really thankful to you. :)

### Proposed solution

remove spec_lock easily. When i do spec_lock 0 then still after 3 4 seconds it locks again.

### Describe alternatives you've considered

remove spec_lock entirely so i can analyze demos with free cam or suggest me a good alternative which i dont know

**Comment by Bubbl666** [comment]
Hi Akiver,

Just a heads up, I'm still experiencing issues with maintaining focus on a single player; it remains random. I've also tried watching some HLTV and FACEIT demos (professional demos, not mine). Also, this issue didn't occur before the last update. Could it be related to this update: feat(playback): allow focusing camera on other players after initial focus [#813](https://github.com/akiver/cs-demo-manager/issues/813)? 

Sometimes, during certain rounds, I can switch to another player's view even though I've selected to watch just one player's view.
Thanks!
