### ISSUE TITLE
Error during installation of CS DEMO Manager 3.5.2 won't create database csdm on initial connection. 

### ISSUE THREAD

**Issue by lorentedford** [akiver/cs-demo-manager#814]
### Describe the bug

During new installation or fresh installation in my case. I followed all the directions to install CSGO Demo manager having already installed Postgres sql previously for other projects I already had the username and password for postgres. 

Here is a screen shot of the error I get. 
![image](https://github.com/akiver/cs-demo-manager/assets/8719903/bd662125-9346-4b67-90f9-866fd63c758c)

Either faulty directions on how to setup the database and it's structure or faulty coding. 

### Steps to reproduce

1. Start with a fresh install.
2. Download  and install Windows 11 Pro.
3. Download and install Steam.
4. Perform all pc updates and upgrades.
5. Download and install [Postgress sql ](https://www.postgresql.org/)
6. Download and install CS DEMO Manager 3.5.2
7. Watch it all explode. 

### Expected behavior

To function as directions Described. 

### How often does this bug happen?

None

### Log file

database "csdm" does not exist

### Environment information

-Version 3.5.2
-OS Windows 11 Pro

**Comment by lorentedford** [comment]
I was able to manually create the database and it worked however. Some how in the installation it did not create the database.

**Comment by wxlvis** [comment]
Removing the leaving the name csdm as empty seemed to have helped me resolve this issue.
