### ISSUE TITLE
Cannot watch demo from CS:DM

### ISSUE THREAD

**Issue by Fantincs** [akiver/cs-demo-manager#818]
### Describe the bug

https://store.steampowered.com/news/app/730/view/4199120329626448730?l=english
This patch from cs2 disable the possibility to watch demo from CS:DM
I can launch any demo from the game, or with HLAE but not with CS:DM
CS:DM was working just before the update yesterday, i was using it at 00:00, and the patch occur at 00:42, and it break

### Demo links

Any demo 

### Steps to reproduce

1- Launch CS DM
2- Upload demo and analyse it 
3- Launch demo from CS DM
4- CS2 start, demo launch and crash mid loading, or just at the start

### Expected behavior

Expected to watch demo, but game keep crash

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/15177224/csdm.log)

### Environment information

Version: 3.5.2
OS: win32 x64 10.0.22631
Electron: 30.0.1
Chrome: 124.0.6367.60
Last database migrations:
v2 - 2024-05-01T14:31:58.068Z

### Additional context

I tried to clean install CSDM with postgresql twice
I tried an old demo, and a fresh demo from after the patch

**Comment by wxlvis** [comment]
Thought I was the only one, seem to be an issue for everyone else I guess?

**Comment by akiver** [comment]
This is probably due to a CS2 interfaces changes.
I'm on vacation so it will be fixed in 2 weeks

**Comment by doxen92** [comment]
> This is probably due to a CS2 interfaces changes. I'm on vacation so it will be fixed in 2 weeks

Demos ware changed in the new update:
*Demo playback will pause at the end of a recording instead of returning to the main menu.
*Minor demo playback optimizations.

awesome ty so much. btw is there a way something I could do myself as a temp. solution til you fix this? 
Ty again for helping the community, you guys rock <3
