### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by Finn-Cedric** [akiver/cs-demo-manager#825]
### Describe the bug

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x12005ee]
![Screenshot 2024-05-07 002603](https://github.com/akiver/cs-demo-manager/assets/145297139/d1ca2429-16c3-4988-96d7-68f7126aa04b)

### Demo links

https://www.faceit.com/de/cs2/room/1-752bcd50-18ae-4379-af6f-802932abd02a

### Steps to reproduce

1. Analyze the demo

### Expected behavior

older demos are working

### How often does this bug happen?

Sometimes

### Environment information

Version: 3.3.0
OS: win32 x64 10.0.22631
Electron: 28.2.3
Chrome: 120.0.6099.283
Last database migrations:
v1 - 2024-05-02T19:53:13.229Z

**Comment by akiver** [comment]
It works fine with the last version, please update the app
