### ISSUE TITLE
Can stop crash while playing demo

### ISSUE THREAD

**Issue by WilliamJong** [akiver/cs-demo-manager#827]
### Describe the bug

After analysis demo watch DEMO via CSDM always crash..
I try many demos this issue always happened.Even cant get into the map.
But I use CS2 to play demo it's nothing wents wrong.
I try to reinstall CSDM,restart computer,close all anticheat include antivirus and crash again.
I used to play demo two weeks ago,it's works well.All function works.
In this two weeks I didnt change the path about demo also CSDM setting & steam setting.
Steam is running without admin rights and the demos is today's demo & I also try the old demo I used to play,but it crashed again.
Is there any possible the bug may related to valorant? But I didnt run valorant while paly the demo & didnt saw the valorant anticheat working in my PC background。

### Steps to reproduce

1.analysis demo
2.play player highlight / other method to play demo via CSDM
3.CS2 running & loading demo
4.CSDM remind me CS2 crashed & CS2 closed without any hint.

### Expected behavior

I would expect demo plays normaly.But I seeing the game always crash.

### How often does this bug happen?

everytime

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/15239686/csdm.log)

### Environment information

-CSDM version: 3.5.2
-CS2 version: latest
-OS:Win10

### Additional context

Could you plz tell me the issue and maybe solution.
Anyway ty for your patience & selflessness.

**Comment by doxen92** [comment]
Duplicate for https://github.com/akiver/cs-demo-manager/issues/818 https://github.com/akiver/cs-demo-manager/issues/817 and https://github.com/akiver/cs-demo-manager/issues/816
@akiver already mentioned that he's on vacation and will fix it once he is back.

**Comment by WilliamJong** [comment]
ty sry that IDK he's on vaction

**Comment by jqdxhs** [comment]
come!come!we are waitng for you !!!@akiver

**Comment by doxen92** [comment]
@jqdxhs let persons enjoy their vacation, they deserve is at anyone else, beside its free and you payed 0 for it comon man stop being a jerk

**Comment by ale-devl** [comment]
> come on!come on!we are waitng for you !!!@akiver

Its open source. Fix it yourself and create a pull request if you can't wait for someone to return from a freaking vacation because you can't watch your highlights.
