### ISSUE TITLE
Play Back Crashes

### ISSUE THREAD

**Issue by F1reD1amond** [akiver/cs-demo-manager#828]
### Describe the bug

When I tried to play back the demo from PerfectWorld (which is a platform like FACEIT in China), the game just kept crushing. The demo analysed well, the data seem to be intact, and is playable in CS2 latest version. The path of the demo is in only latin characters, and the system/game language is in English.

### Demo links

https://1drv.ms/u/s!AnTV-uz-VTXGzAXHNNXQlWBFpnOR?e=eCMHk2

### Steps to reproduce

1. Launch the CS demo manager
2. Analyse the file
3. Replay
4. Game crashes

### Expected behavior

I would expect the game to run just fine, but I saw the game crashed

### How often does this bug happen?

None

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/15245295/csdm.log)

### Environment information

Version: 3.5.2
OS: win32 x64 10.0.22631
Electron: 30.0.1
Chrome: 124.0.6367.60
Last database migrations:
v2 - 2024-05-08T14:57:14.710Z

**Comment by akiver** [comment]
dup #818
