### ISSUE TITLE
Adjust 2D viewer Timer

### ISSUE THREAD

**Issue by DrOetcker** [akiver/cs-demo-manager#830]
### What problem is this solving

When looking at the 2D viewer it would be nice if the timer could represend the real time of the game.
For now it is really complicated to calculate at what timestamp in the Round player reaches a certain point.

Example Basic Infos:
Competitive RoundTime: 1:55min
Round time in total: 2:20min Incl warmup
Warumup 15sec

Event 1 Round start after warmup:
- Round start: Timer shows 2:05
- Round Processbar shows 0:15
- Real elapsed Round Time: 0:00
- Real Round Timer ingame: 1:55

Event 2 Player X reaches certain interesting point:
- Round start: Timer shows 1:32
- Round Processbar shows 0:47
- Real elapsed Round Time: 0:33
- Real Round Timer ingame: 1:22

Event 3 Bombplant:
- Round start: Timer shows 0:47
- Round Processbar shows 1:32
- Real elapsed Round Time: 1:18
- Real Round Timer ingame: 0:37

We see here, that calculating the time which is interesting on a review (Real elapsed Round Time/Real Round Timer ingame) often can be confusing to determine.

To be able to get this info faster and more comfortable I would suggest adding another timer on top of the 2D viewer next to the existing timer.

### Proposed solution

As the GameMode (Comp, Causal etc) is known, I would suggest, that an additional timer is added to the UI next to the existing Timer.
Im not sure if the data of a demo can provide the roundtime (For competitive eg 1:55), but if so, this timer as an additonal Timer in the UI could help teams to improve their strats against other teams when reviewing Demos.

In case the Bomb gets planted, I would suggest to do it like ingame. Either set the new added timer to "0:00"/"-:--" or hide it completly

Imho: Adding the Real Round Timer (counting down from 1:55 in competitive) would be the prefered solution.

### Describe alternatives you've considered

If the data of a demo does not provide the roundTimer, I would suggest, at the "Generate Positions"-UI, add an additional, optional (default 1:55 for competitive) Field to add the time of a round to the DB entry of the demo

**Comment by DrOetcker** [comment]
![suggestion](https://github.com/akiver/cs-demo-manager/assets/25843766/72c75a79-2d8c-4aad-9d11-ed2e6b6c8330)

**Comment by akiver** [comment]
I don't think there is an accurate way to detect `mp_roundtime`, the new version also shows the elapsed time since the end of the freezetime.
