### ISSUE TITLE
"Delete from Database" in Demo tab not working

### ISSUE THREAD

**Issue by Rebze** [akiver/cs-demo-manager#836]
### Describe the bug

While in the Demo tab, the option "Delete from database" does not work. The Delete action in the Matches tab does work though.

### Steps to reproduce

1. Start CS Demo Manager
2. Go to "Demos"
3. Right click on a demo
4. Select "Delete from database"
5. Select "Confirm"

### Expected behavior

I would expect the demo gets deleted from the database, but it does not

### How often does this bug happen?

Every time

### Environment information

- Version: 3.5.3
- OX: win32 x64 10.0.19045
- Electron: 30.0.3
- Chrome: 124.0.6367.119

**Comment by akiver** [comment]
The demo is deleted but then re-inserted as the list is refreshed when it's done.
We could not refresh the list but I don't see the benefit as demos paths are stored in the database to speed up loading time.
What's your use case?

**Comment by Rebze** [comment]
I use CS Demo Manager to look at aggregated data for maps. Community maps
that are in development can benefit incredibly from e.g. seeing which bomb
site gets more plants, which hostage gets rescued most successfully. While
I was looking through the data I noticed some discrepancy with hostage
entity ids, tried to quickly single out which game they came from and
expected that Delete button to actually delete the game from the database,
rather than refresh it - just like it does when you use the Delete option
in the Matches tab.
I didn't expect 2 different behaviors for buttons that both say "Delete",
which got me to assume it's a bug

AkiVer ***@***.***> schrieb am Do., 16. Mai 2024, 04:01:

**Comment by akiver** [comment]
> expected that Delete button to actually delete the game from the database, rather than refresh it - just like it does when you use the Delete option in the Matches tab.
I didn't expect 2 different behaviors for buttons that both say "Delete", which got me to assume it's a bug

The "Demos" and "Matches" tabs are related but are 2 distinct entities.
The "Demos" tab shows the demos on your filesystem while the "Matches" tab shows the matches stored in the database (i.e. data extracted from `.dem` files).
The "Delete" option of the "Matches" tab deletes the matches data from the database. <- this is what you want to do I guess
The "Delete" option of the "Demos" tab deletes the demos from the filesystem.
The "Delete from database" option of the "Demos" tab deletes the demos data from the database. This data includes the demo locations on the filesystem and a few information coming from `.dem` files header (game, map name...).
Demos data are also stored in the database to avoid reading the files every time to improve loading time.
You can delete it to "clear the cache" and retrieve fresh demos data.

Does this help?
