### ISSUE TITLE
[Feat] Add a weapon slelction option in search

### ISSUE THREAD

**Issue by rong-xiaoli** [akiver/cs-demo-manager#841]
### What problem is this solving

When I want to get some hilarious moment I found it difficult to find taser kill part, I have to enter the specific match and find taser kills in each round. So I guess maybe there is a better solution?

### Proposed solution

In "search" page, there can be a weapon selection option.

**Comment by akiver** [comment]
The `Knife kills` event in the "Search" page filter on knife **and** tazer kills.
The label will be clearer in the next release.

![2024-05-19 at 15 18 16](https://github.com/akiver/cs-demo-manager/assets/1842524/70336513-9db5-4e33-b23c-e58410598ae3)

**Comment by rong-xiaoli** [comment]
OK thanks.
