### ISSUE TITLE
After the update CS Demo Manager can no longer generate videos

### ISSUE THREAD

**Issue by woshisheinihao** [akiver/cs-demo-manager#848]
### Describe the bug

After the update CS Demo Manager can no longer generate videos
<img width="1278" alt="屏幕截图 2024-05-24 113045" src="https://github.com/akiver/cs-demo-manager/assets/114495375/ac2ab292-061b-4c98-b194-30bb417414fb">

### Steps to reproduce

<img width="1278" alt="屏幕截图 2024-05-24 113045" src="https://github.com/akiver/cs-demo-manager/assets/114495375/bb1e2b62-663b-4980-a633-f524ab69587b">

### Expected behavior

I want to know how to solve this problem

### How often does this bug happen?

None

### Environment information

rog g14 2023
win11
css2
![Uploading 屏幕截图 2024-05-24 120404.png…]()

**Comment by Felixitus** [comment]
I ran in the same Error

**Comment by akiver** [comment]
The error comes from HLAE, not the app.
Please read the doc https://cs-demo-manager.com/docs/guides/video#hlae.
You have to keep HLAE up-to-date.

**Comment by RomanoHodysh** [comment]
Strange because HLAE is updated same as FFmpeg
![image](https://github.com/akiver/cs-demo-manager/assets/32075919/f00dcd8e-9f40-407e-a10a-f6d1c701f6fb)
