### ISSUE TITLE
Export nade explosion coordinates

### ISSUE THREAD

**Issue by Dying-Ducks** [akiver/cs-demo-manager#850]
### What problem is this solving

I basically build my own version of your heatmap so that I can display information from multiple demos. For that I use the .json export from the single demos and "put them together" afterwards. 

While doing so I noticed I can recreate the kills/deaths heatmap section and the Opening duels map. 
But I can’t rebuild the Grenades > Finder section, as I only found the position where nades where thrown (out of the exported shot.ts). I can’t find the location information where the nades exploded anywhere in the .json export.

While looking at the code for it, I believe that I would need the "[nadetype]-exlode.ts" data from src/common/types/. Also I would probably need the "grenade-bounce" coordinates.

### Proposed solution

Add the explosion location information and bounce information (and maybe every other coordinate data that is needed in creating the Grenades > Finder section that I missed) in the .json export of a demo

**Comment by akiver** [comment]
The next version will contain an array of grenade explode events but it's recommended to do your own [SQL export](https://cs-demo-manager.com/docs/guides/export) as it's not possible to fit everyone's needs.
