### ISSUE TITLE
Group Tab

### ISSUE THREAD

**Issue by D3XX3R** [akiver/cs-demo-manager#858]
### What problem is this solving

When I want to check how my group (me and the pre-mates I queued with, excluding randoms) performed as a whole, I have to check, how every single player has performed and put the data together in my head to have an understanding what our performance was. Having the Teams Tab is great for Faceit Matches (if you are the leader and can name the Team) but that doesn't work for regular CS2 matchmaking and doesn't exclude other players.

### Proposed solution

This is why I propose the "Group Tab". It introduces a new separate Tab right below your personal overview, which consists of all the stats you have collected in matches with your group. For a match to be added to said group tab, it has to consist of at least two group members. To add a player to your group, you get into the players tab and have a new button "Add player to group" right below "Pin this player".

**Comment by akiver** [comment]
You can already do it by giving a unique name to your team from the matches list.

![d](https://github.com/akiver/cs-demo-manager/assets/1842524/ad189dd0-64cd-4bdd-9559-b3cc766ee116)

**Comment by D3XX3R** [comment]
Good to know, but this only really works if you are in a 5 stack team. Otherwise you will have stats from random players also fed into your team statistics.
