### ISSUE TITLE
Highlights/Lowlights not working after today.

### ISSUE THREAD

**Issue by jakehall4452** [akiver/cs-demo-manager#860]
### Describe the bug

I've been using CSDM to watch highlights/lowlights from both POVs of my matches. Yesterday, I was able to do this just fine. Today, I try and watch my highlights of my matchmaking games, and it just loads the demo as normal and plays it from start to finish without forcing any POV or skipping to any kills. AFAIK there hasn't been an update to CS2 since the 29th, which would've been before CSDM was working for me at the time. CSDM's recent update also came before it was last working for me.

### Steps to reproduce

1. Start the application
2. Select a demo ---> See match ---> Right click player ---> Watch > Highlights
3. Wait for CS2 to launch and the demo to load

### Expected behavior

The demo should open and queue all of the selected player's highlights from the POV selected.

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/user-attachments/files/15513429/csdm.log)

### Environment information

Version: 3.6.1
OS: win32 x64 10.0.22631
Electron: 30.0.8
Chrome: 124.0.6367.230
Last database migrations:
v2 - 2024-04-05T06:15:11.131Z

### Additional context

I've restarted my computer, re-installed PostgreSQL & CSDM, and verified integrity of game files. Due to there not being an update to CS2 nor CSDM since this bug started happening, it's possible that it's an issue on my end - however, I have not changed anything in my environment that would've caused this manually. I watched some highlights before going to bed in the morning, and woke up to them not working. Both new and old highlights (that were working before) are having the same issue.

**Comment by mini337** [comment]
Same issue.

**Comment by syko** [comment]
+1 one of my favourite features of the app

**Comment by pingadom** [comment]
Same issue here

**Comment by wongchong** [comment]
same

**Comment by roustar31** [comment]
use HLAE 2.163.4 will be fine
https://github.com/advancedfx/advancedfx/releases/tag/v2.163.4

**Comment by roustar31** [comment]
Maybe also use CS2 1.40.1.0

**Comment by jakehall4452** [comment]
> use HLAE 2.163.4 will be fine https://github.com/advancedfx/advancedfx/releases/tag/v2.163.4

> Maybe also use CS2 1.40.1.0

Launching with that HLAE version crashes my game instantly. Launching with that CS2 version gives me an error after trying to load the demo. Using both, the game doesn't crash but the demos don't load. This happens for both new and old demos.
