### ISSUE TITLE
An error when i'm going to analyze the demo

### ISSUE THREAD

**Issue by hurtboli** [akiver/cs-demo-manager#862]
### Describe the bug

Nothing special , Click to analyze , Under 1 Second , Error , just like this

### Demo links

https://drive.google.com/file/d/1V3nPGmbbPCG3pBPZt_dgmLCNnYzNyv12/view?usp=sharing

### Steps to reproduce

I just tried to analyze the demo but report error like this

```
panic: unknown message type 76 [recovered]
	panic: unknown message type 76

goroutine 1 [running]:
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.recoverFromUnexpectedEOF({0x4660e0, 0xc00097bb10})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:171 +0xd7
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd.func1()
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:124 +0xa5
panic({0x4660e0?, 0xc00097bb10?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleDemoPacket(0xc0002d0a80, 0x761b?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/s2_commands.go:346 +0x54e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc0002d0a80)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:378 +0x306
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc0002d0a80)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc00013803b, 0x21}, {0xe0?, {0xc00012e038?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:226 +0xb35
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc00013803b?, 0x21?}, {0xc00013c0c8, 0x31}, {0x0, {0xc00012e038, 0xc}, {0xc00011a0c8, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:270 +0x6c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc000142010, 0x4, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45
```

### Expected behavior

nothing but the error are shown here

### How often does this bug happen?

Every time

### Environment information

Version: 3.5.2
OS: win32 x64 10.0.19045(Windows 10 x64)
Electron: 30.0.1
Chrome: 124.0.6367.60

**Comment by syko** [comment]
FYI I got the same error when trying to analyse a demo from private matchmaking but upgrading to v3.6.1 seems to have fixed it

**Comment by akiver** [comment]
please update the app

**Comment by hurtboli** [comment]
Thank you I fixed it XD:)
________________________________
发件人: Andrin Riiet ***@***.***>
发送时间: 2024年6月1日 23:58
收件人: akiver/cs-demo-manager ***@***.***>
抄送: hurtboli ***@***.***>; Author ***@***.***>
主题: Re: [akiver/cs-demo-manager] An error when i'm going to analyze the demo (Issue #862)


FYI I got the same error when trying to analyse a demo from private matchmaking but upgrading to v3.6.1 seems to have fixed it

―
