### ISSUE TITLE
Unable to analyze

### ISSUE THREAD

**Issue by 6Gaster-maker** [akiver/cs-demo-manager#864]
### Describe the bug

Unable to analyze my demo.

### Steps to reproduce

1.Open my demo
2. Click "Analyze"
4. Directly display "Analysis Error"

### Expected behavior

When analyzing my demo, I get an error.

### How often does this bug happen?

Often

### Log file

panic: unknown message type 76 [recovered]
	panic: unknown message type 76

goroutine 1 [running]:
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.recoverFromUnexpectedEOF({0xff60e0, 0xc000bea2b0})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:171 +0xd7
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd.func1()
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:124 +0xa5
panic({0xff60e0?, 0xc000bea2b0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleDemoPacket(0xc00028b500, 0x6718?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/s2_commands.go:346 +0x54e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc00028b500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:378 +0x306
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc00028b500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc0000420ab, 0x8b}, {0xe0?, {0xc00000a158?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:226 +0xb35
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc0000420ab?, 0x8b?}, {0xc00002e248, 0x31}, {0x0, {0xc00000a158, 0x5}, {0xc00000a128, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:270 +0x6c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc000046090, 0x4, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45

### Environment information

Version: 3.5.3
OS: win32 x64 10.0.26120
Electron: 30.0.3
Chrome: 124.0.6367.119
Last database migrations:
v2 - 2024-05-20T23:30:38.226Z

**Comment by akiver** [comment]
please update the app
