### ISSUE TITLE
Add modifier for highlights/lowlights to also support damage given which not results in a kill

### ISSUE THREAD

**Issue by holgerschillack** [akiver/cs-demo-manager#869]
### What problem is this solving

When I click on view highlights/lowlights of a player I want to have a checkbox which says `also include damage given without a kill` so I would also see the occurances of successfull wallbangs/awp shots through doors in the demo summary.

### Proposed solution

see above

**Comment by akiver** [comment]
> also include damage given without a kill

So **any** damages done would be included?
I don't think that should be considered a "highlight".

If it's only about wallbang shots that did more than let's say 40 damages, I think that's ok.

**Comment by holgerschillack** [comment]
Yes e.g. if you do more than ~40 dmg would be a nice cut off value to take into consideration for the highlights summary.

It's about wallbang shots and headshots with <100hp damage. E.g. an awp hit through the dust2 doors from t spawn would be nice to be notified about.

And as said of course the whole thing as an option to opt in.

**Comment by holgerschillack** [comment]
Do you know when the next release (with this feature) will be deployed?
