### ISSUE TITLE
Weapon death count misleading

### ISSUE THREAD

**Issue by ttikkanen** [akiver/cs-demo-manager#88]
I just analyzed 15+ demos from our clan games. I see suspiciously low and high K/D ratios for certain weapons, while more common weapons seem more trustworthy. Does it count deaths as 

**Killed by weapon X** 
OR 
**Killed while wielding weapon X?**

The first option could partly explain the weirdness. But it would not describe weapon effectiveness well. Details:
- Friend 1 has 1/46 with AWP
- Friend 2 has 3/41 with AWP
- Friend 3 has 86/16 with M4
- I have 50/11 with CZ

**Comment by akiver** [comment]
It's "killed by weapon".
For friend 1, it means he killed 1 enemy with an AWP and he has been killed 46 times by enemies with an AWP.
These stats are from all demos where friend 1 played, so it looks like he doesn't play with AWP often.

If you find a demo where kill count are incorrect, please upload it.

**Comment by ttikkanen** [comment]
"Killed by weapon" is not nearly as relevant as "killed while wielding weapon". Is the latter going to be implemented?

**Comment by akiver** [comment]
It's not my priority but I will add it later, thanks.

**Comment by akiver** [comment]
A new major version has been released, closing the issue 🧹
