### ISSUE TITLE
Can't generate video for first round in each demo

### ISSUE THREAD

**Issue by RomanoHodysh** [akiver/cs-demo-manager#881]
### Describe the bug

Can't generate video for first round in each demo. Demo just stucks on one moment and is replayed for 1 second long in a loop.

### Steps to reproduce

1. Start the app
2. Select Demo
3. Create new sequence for first round only
4. Save
5. Click Generate

Logs: [csdm.log](https://github.com/user-attachments/files/15928548/csdm.log)

### Expected behavior

Video is generated without issues

### How often does this bug happen?

Always

### Log file

Fri, 21 Jun 2024 13:32:44 GMT | LOG | renderer | WS:: message with name "concatenate-videos-success" received from server
Fri, 21 Jun 2024 13:33:08 GMT | LOG | server | WS:: message with name update-checksums-tags and uuid 76d913b4-8d94-4907-920c-47fff5a508ea received from renderer process
Fri, 21 Jun 2024 13:33:10 GMT | LOG | server | WS:: message with name load-demo-by-path and uuid a4463556-53a9-4692-8682-64a8f03eb7a2 received from renderer process
Fri, 21 Jun 2024 13:33:15 GMT | LOG | server | WS:: message with name fetch-match-by-checksum and uuid dc7c56ca-aa0e-4fe9-9689-fe24de1750d9 received from renderer process
Fri, 21 Jun 2024 13:33:17 GMT | LOG | server | WS:: message with name initialize-video and uuid ea675c0d-3bf8-4dc6-8aec-79c4446875b1 received from renderer process
Fri, 21 Jun 2024 13:38:40 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid 32920e08-2e0b-4318-beb7-79d5b8ec3000 received from renderer process
Fri, 21 Jun 2024 13:40:01 GMT | LOG | server | WS:: message with name is-cs-running and uuid b0b027c9-2c63-422e-aeda-c2ac83316c5b received from renderer process
Fri, 21 Jun 2024 13:40:01 GMT | LOG | server | WS:: message with name generate-videos and uuid 0f4d2998-f574-441e-9ef0-c230e196a4c7 received from renderer process
Fri, 21 Jun 2024 13:40:01 GMT | LOG | server | Starting HLAE with command "C:\Users\roman\.csdm\hlae\hlae.exe" -noGui -autoStart -afxDisableSteamStorage -customLoader -hookDllPath "C:\Users\roman\.csdm\hlae\x64\AfxHookSource2.dll" -programPath "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe" -cmdLine "-insecure -novid +playdemo \"C:\program files (x86)\steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\replays\match730_003685392135391019335_1324391167_191.dem\" -width 2560 -height 1440 -sw"
Fri, 21 Jun 2024 13:40:03 GMT | LOG | server | HLAE exited with code 0
Fri, 21 Jun 2024 13:40:06 GMT | LOG | server | WS:: game process socket connected
Fri, 21 Jun 2024 13:40:55 GMT | LOG | server | WS:: game process socket disconnected 1006 { type: 'Buffer', data: [] }
Fri, 21 Jun 2024 13:41:04 GMT | ERROR | server | Recording folder does not exist C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\csdm\movie
Fri, 21 Jun 2024 13:41:04 GMT | ERROR | server | Error: Raw files not found
    at iVe (C:\Users\roman\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\sequences\move-sequences-raw-files.ts:35:11)
    at oVe (C:\Users\roman\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\generate-videos.ts:273:5)
    at sVe (C:\Users\roman\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\generate-videos-handler.ts:56:5)
    at t.onRendererProcessSocketMessage (C:\Users\roman\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:177:26)
Fri, 21 Jun 2024 13:41:04 GMT | ERROR | server | Error while generating videos
Fri, 21 Jun 2024 13:41:04 GMT | LOG | renderer | WS:: message with name "videos-generation-error" received from server
Fri, 21 Jun 2024 13:44:30 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid 0cd0730a-c3f6-4143-a168-f1d81d9c52cd received from renderer process

### Environment information

Version: 3.6.3
OS: win32 x64 10.0.22631
Electron: 30.0.9
Chrome: 124.0.6367.233
Last database migrations:
v3 - 2024-06-05T10:47:43.914Z
v2 - 2024-04-04T18:38:16.272Z
v1 - 2023-12-12T01:12:49.001Z

**Comment by akiver** [comment]
Could you try with the new v3.7.0?
If you still have the issue, please upload an affected demo and detailed steps to reproduce it.

**Comment by RomanoHodysh** [comment]
In new version it's generates video but shows incorrect player.

**Comment by akiver** [comment]
> In new version it's generates video but shows incorrect player. But it's not a big problem because you may change player with single click

Did you re-analyze the demo? See the warning in the changelog https://cs-demo-manager.com/changelog#v370

**Comment by RomanoHodysh** [comment]
Sorry, you are right. I re-analyzed the demo and now all good. Thank you very much :)
