### ISSUE TITLE
Error parsing pov files

### ISSUE THREAD

**Issue by Xiguinilster** [akiver/cs-demo-manager#883]
### Describe the bug

Previously it allowed you to analyze POV files recorded with the console. I wanted to analyze some and there was no solution to analyze them.
I have already tried changing all the sources

### Demo links

-

### Steps to reproduce

-

### Expected behavior

-

### How often does this bug happen?

None

### Log file

-

### Environment information

-

### Additional context

-

**Comment by akiver** [comment]
dup https://github.com/akiver/cs-demo-manager/discussions/882
