### ISSUE TITLE
New Wingman/Normals Maps

### ISSUE THREAD

**Issue by GeneralBombe** [akiver/cs-demo-manager#884]
### What problem is this solving

I cant find the map data in resource/overviews in the pak01_dir.vpk file. Can someone help me out how to add those maps? 

### Proposed solution

Or are those maps saved anywhere else and could i add them that way?

**Comment by akiver** [comment]
You must open the `map_name.vpk` file located in the `maps` folder.

I will update the [doc](https://cs-demo-manager.com/docs/guides/maps#addingediting-a-map) later and the next version will include the new maps.

**Comment by akiver** [comment]
The doc has been updated https://cs-demo-manager.com/docs/guides/maps.
