### ISSUE TITLE
Option or default not to overwrite user's HLAE config

### ISSUE THREAD

**Issue by ChetdeJong** [akiver/cs-demo-manager#886]
### What problem is this solving

Probably not everyone is happy with having CSDM overwrite their HLAE config.

### Proposed solution

I added `-noConfig` parameter to HLAE interfaces a while ago, that solves this issue.
https://github.com/advancedfx/advancedfx/releases/tag/v2.163.0

**Comment by akiver** [comment]
It seems redundant with the current option to define the "movie making config parent folder" (`-mmcfg`) no?

**Comment by ChetdeJong** [comment]
I meant the HLAE config itself, not moviemaking.

To see what I mean open HLAE, then go into tools > developer > custom loader. Remember the parameters, close HLAE. 

Then run CS2 with CSDM e.g. open some demo, close CS2 and check these parameters in HLAE again. Whatever was there was overwritten by CSDM

**Comment by akiver** [comment]
I see, that's the HLAE launcher config, I think I will pass the `-noConfig` by default.
Thanks
