### ISSUE TITLE
Change Source dropdown stopped working

### ISSUE THREAD

**Issue by milkywayfarer** [akiver/cs-demo-manager#891]
### Describe the bug

When trying to change demo source, the Change Source dropdown does not work when clicking on it. This was not the case in previous updates.

### Steps to reproduce

1. Add a demo from Valve
2. Try to analyze it, but it requires you to specify the demo source
3. Clicking on a dropdown does nothing

### Expected behavior

Dropdown is working and I'm able to change the source

### How often does this bug happen?

Every time

### Environment information

Version: 3.7.0
OS: darwin x64 23.5.0
Electron: 31.1.0
Chrome: 126.0.6478.114
Last database migrations:
v4 - 2024-07-01T10:09:04.414Z
v3 - 2024-06-10T09:56:39.352Z
v2 - 2024-04-03T07:26:11.347Z
v1 - 2023-12-27T07:44:27.131Z

**Comment by milkywayfarer** [comment]
Tried to downgrade to confirm regression, but it just dropped my whole database with a whole year of data.

**Comment by milkywayfarer** [comment]
Regression confirmed - dropdown works in 3.6.3

**Comment by akiver** [comment]
do you mean this dropdown?
![d](https://github.com/akiver/cs-demo-manager/assets/1842524/178407cc-16e9-4fc8-9f2d-d6cf66f550dd)

It works fine for me

**Comment by milkywayfarer** [comment]
Yeah, just updated from 3.6.3 to 3.7.0 again and dropdown stopped working. Don't really know what happened, maybe macOS shenanigans.

Also, downgrading while having a newer database schema version should yield an error, not drop the database and remigrate it again. But that's an enhancement, not an issue at hand :)

**Comment by akiver** [comment]
The next version will warn and ask before resetting the database.
