### ISSUE TITLE
Bomb Explosion After Round End

### ISSUE THREAD

**Issue by Dying-Ducks** [akiver/cs-demo-manager#896]
### Describe the bug

If the bomb exploded during the round restart delay it will be falsely determined that the end reason was the bomb explosion. 

The other day I worked on a demo and noticed following: 
![Screenshot 2024-07-19 200330](https://github.com/user-attachments/assets/683638c6-b366-4eaf-97a3-1c0585366fa4)
According to the Demo Manager Round 9 ended because of the bomb explosion.

But in fact, round 9 ended because of the T's killed all the CT's, as shown in the Scoreboard in game:
![Screenshot 2024-07-19 192947 - Kopie](https://github.com/user-attachments/assets/aa2763ee-128f-47e4-a86b-97e24032cee3)

I checked the demo manager data and the bombs_exploded table and the rounds table showed for the ticks:
bombs_exploded tick: 65287
end_tick: 64977
end_officially_tick: 65425

As the exlosion tick is right between the both "end ticks" I suspect that the end_tick is the tick the round ended, and the end_officially_tick is the tick the round restarts. 

And I think that the demo mananger used falsly the end_tick instead of the end_officially_tick to determined the end_reason in the rounds table, as this was set to 1 (TargetBombed) for this round. 

### Steps to reproduce

Analyse a demo that happend to have a bomb explosion right after the last kill and before the round restarts.

### Expected behavior

Demo Manager should detect the correct (as shown in the ingame scoreboard) round end reason.

### How often does this bug happen?

None

### Environment information

Version: 3.6.3
OS: win32 x64 10.0.19045
Electron: 30.0.9
Chrome: 124.0.6367.233
Last database migrations:
v3 - 2024-07-11T13:09:40.438Z

**Comment by akiver** [comment]
Could you upload the demo please?
