### ISSUE TITLE
Change Player Name

### ISSUE THREAD

**Issue by dbalders** [akiver/cs-demo-manager#897]
### What problem is this solving

When looking at demos, sometimes on faceit people can have streamer mode on, or they change their steam name for a few matches for fun. Would be nice to be able to change that person's name in the overview so instead of the player being 'Pirojenka-' they can be labeled as 'Ax1le'.

### Proposed solution

In the demo overview, right click on a player and hit 'Change Name' and change it to a new name and have it populate through the stats and the 2d viewer.

**Comment by dbalders** [comment]
I noticed you can right click on the player with the fake name and go to their profile and it shows their normal steam name. Maybe possible to just grab that as an option?

**Comment by akiver** [comment]
The next version will allow overriding players' nicknames from scoreboards or the players list through the right-click context menu.

**Comment by dbalders** [comment]
Thank you!!
