### ISSUE TITLE
Multi Select for 2D Viewer

### ISSUE THREAD

**Issue by dbalders** [akiver/cs-demo-manager#898]
### What problem is this solving

Right now you can multi select and analyze multiple demos in a row. But, in order to also do the 2D viewer generation, you have to go into each one and hit 'Generate Positions'.

### Proposed solution

Either another option when right clicking to do the Generate Positions, or an option when hitting analyze to also do those with hit.

**Comment by akiver** [comment]
There is already an option from the app settings to globally generate positions during analyses.

![f (2)](https://github.com/user-attachments/assets/75d6a06d-9915-4ace-948b-41243bdb92de)

**Comment by dbalders** [comment]
Ah, im sorry didn't see that! Thanks!
