### ISSUE TITLE
Player Video Generation Issue

### ISSUE THREAD

**Issue by PxrpleCode** [akiver/cs-demo-manager#910]
### Describe the bug

When setting up a players POV and starting the recording process the demo will load up but it always has an issue with demoui still being visible and also not correctly choosing the player assigned in the sequences settings. 

Example: These are the settings I would use to record the POV. I selected ultimate's pov but once I start the process it is not working properly (see 2nd image) 
![Screenshot_2](https://github.com/user-attachments/assets/858e057a-3019-464e-98e6-a920926484ed)

![Screenshot_3](https://github.com/user-attachments/assets/7272eec7-b707-4538-9627-b268aa7d5e68)

### Demo links

Any demo at the moment.

### Steps to reproduce

Select user to generate full round POV
start queue

### Expected behavior

The demoui should not be visible and the wrong player shouldn't be recorded.

### How often does this bug happen?

Every time

### Environment information

Version: 3.7.1
Windows 11 

### Additional context

I have also tried manually removing demoui and changing the player but it completely messes up the recorded file - it will keep the first round completely speed up.

**Comment by akiver** [comment]
1. Could you please share the demo?
2. Could you share your autoexec? It may be due to a command that opens the demo ui

**Comment by ChetdeJong** [comment]
I have found that it depends on `demo_ui_mode` user has set. In some cases it can conflict with CSDM "fix".

I suggest removing `demoui` execution from CSDM and executing `demo_ui_mode 0` instead, **before(!)** demo is loaded. Then demoui should not appear in all cases.

https://github.com/akiver/cs-demo-manager/blob/83dd0d6968b50a065e335a2fa9c902a2b07ade23/src/node/counter-strike/json-actions-file/json-actions-file-generator.ts#L99

**Comment by ChetdeJong** [comment]
> Can I change this myself? Or do I have to wait for an update?

Yeah, load game, set `demo_ui_mode 2` and close it. Then I think it should work fine with current CSDM fix. Basically it will load demo with demoui open and then CSDM will close it

**Comment by akiver** [comment]
> **before(!)** demo is loaded

This was the important thing, I tried during playback - thanks it will be fixed in the next release.

**Comment by iKryxx** [comment]
Sorry for the reopen, but I have the same issue. When I try to record with HLAE, the demo opens but doesn't jump to the sequences/camera views. When I start the recording without HLAE (setting recording method to Counter Strike), it works fine.

**Comment by SammyTeee** [comment]
same for me re: @iKryxx comment above - anybody have any idea how to fix?

**Comment by sgrochowski** [comment]
I am encountering a similar issue where some of the DemoUI stays visible on the screen on occasional launches of either video recordings with HLAE or just "watching" rounds, and it'll not focus on the right player/round. "Disconnecting" from the demo immediately fixes this issue for me but this becomes a pain when bulk processing videos. The script I use to interface with CSDM is able to circumvent this via watching the output and making sure it's growing, but it's a hacky fix.

**Comment by akiver** [comment]
Please open a new issue with the demo + steps to reproduce the issue.
