### ISSUE TITLE
Default timestamp for analyzed matches

### ISSUE THREAD

**Issue by milkywayfarer** [akiver/cs-demo-manager#915]
### Describe the bug

When analyzing a demo, it receives a default timestamp in UTC (`1/1/1970, 5:00:00 AM`, I'm in +5 zone).

### Demo links

https://cloud.mway.club/s/jDoFtqPYXdLsLLc

### Steps to reproduce

1. Analyze the demo

### Expected behavior

I would expect the timestamp to at least match the filename

### How often does this bug happen?

None

### Environment information

Version: 3.8.0
OS: darwin x64 24.0.0
Electron: 31.3.1
Chrome: 126.0.6478.185
Last database migrations:
v5 - 2024-08-21T06:10:44.808Z
v4 - 2024-08-08T16:29:56.767Z
v1 - 2024-08-08T16:29:20.861Z

**Comment by akiver** [comment]
Thanks for the report - it's fixed in v3.8.1.
You have to re-analyze demos to update the date.
