### ISSUE TITLE
Wrong Team

### ISSUE THREAD

**Issue by qspqww** [akiver/cs-demo-manager#921]
### Describe the bug

Wrong team for somebody who quit at the beginning of the match
There are two orange in a team
![image](https://github.com/user-attachments/assets/8d49aac0-e8de-4d5c-a3ad-9d239de9b1a1)

### Steps to reproduce

1. somebody quit before match eventually start and rejoined
2. import and analyse with the viewer
3. the team members got wrong

### Expected behavior

I would expect that both teams have 5 players

### How often does this bug happen?

Often

### Environment information

Version: 3.8.1
OS: win32 x64 10.0.26231
Electron: 31.4.0
Chrome: 126.0.6478.234
Last database migrations:
v5 - 2024-08-25T12:00:57.116Z
v4 - 2024-08-02T18:04:54.181Z

**Comment by akiver** [comment]
Please upload the demo so we can work on it

**Comment by qspqww** [comment]
https://drive.google.com/file/d/10ycjWkDict1rao4CzIOGIXGdVOO5kb5T/view?usp=drive_link

**Comment by akiver** [comment]
@qspqww the file is private
