### ISSUE TITLE
analyze data is wrong when restore backup file using command "mp_backup_restore_load_file"

### ISSUE THREAD

**Issue by jaredliu2018** [akiver/cs-demo-manager#922]
### Describe the bug

when restore previous round, analyze data is not correct. "Round Number" is wrong and player kills before/after restore is mixed 

### Demo links

https://cdn.b5csgo.com.cn/b5demo/demos/b5match_6047572754428608755.dem.zip

### Steps to reproduce

1. Start demo manager
2. analyze demo
3. check analyze data

### Expected behavior

correct analyze data when restore previous round.

### How often does this bug happen?

None

### Environment information

None.

**Comment by akiver** [comment]
Where does this demo come from?
3.1MB for a CS2 match is unusual, even the CS2 client crashes when trying to play it.
Demos recorded manually are not supported (see the [doc](https://cs-demo-manager.com/docs/guides/demos-analysis#what-are-the-supported-demo-sources))

**Comment by jaredliu2018** [comment]
OK
I will close this issue.
