### ISSUE TITLE
How to switch camera focus multiple times in a sequence.

### ISSUE THREAD

**Issue by JarmoHu** [akiver/cs-demo-manager#923]
### What problem is this solving

**translated by Google:**
How to switch camera focus multiple times in a sequence.
This question has been mentioned before #902 and marked as solved. But I think it can be solved more perfectly.
Usage scenario: For example, if I kill multiple enemies in a short period of time, I want to generate videos from the enemy's perspective in sequence. Due to the short time interval, it can only be played in one sequence, but currently only one enemy's perspective can be focused.

original:
如何在一段sequence中多次切换camera focus。
这个问题之前提到过 #902 ，并被标记为已解决。但是我觉得可以解决的更加完美。
使用场景：比如我在较短的时间内连续击杀多个敌人，我想依次从敌方视角生成视频。由于时间间隔较短，只能在一个sequence中播放，但是目前只能集中于一个敌人的视角。

### Proposed solution

A perspective switching indicator can be inserted in the sequence.

### Describe alternatives you've considered

none

**Comment by ReneRebsdorf** [comment]
Would it be possible with this, to also say "this same kill, from both killer and killed perspective"?
Ideally it would be great if the demo generator allowed multiple clips at the same timestamp, from different POVs
