### ISSUE TITLE
Add a CLI option to automatically record clips

### ISSUE THREAD

**Issue by 1033095780** [akiver/cs-demo-manager#926]
### What problem is this solving

Add a CLI option to automatically record clips

### Proposed solution

I'm using Selenium to operate csdm to batch-generate video clips. Would it be possible to add a CLI option that allows for the following: input the demo path, start and end ticks, video resolution, and frame rate, and then directly generate the output?

some players encounter two options when launching CS. add '-worldwide' to the default launch options. This wouldn't affect current users and would save others from having to manually select the option.

AND Thank you for this amazing project! CSDM has helped me a lot.

**Comment by akiver** [comment]
dup https://github.com/akiver/cs-demo-manager/issues/722
