### ISSUE TITLE
Big data statistics of players and teams from a POV

### ISSUE THREAD

**Issue by Xiguinilster** [akiver/cs-demo-manager#934]
### What problem is this solving

-

### Proposed solution

-

### Describe alternatives you've considered

Is it possible to add the data analysis function of a POV only for the team and player data in order to extract metrics from the training sessions?

**Comment by akiver** [comment]
I can't understand your feature request.
Please follow the feature request template and provide more information/details.

**Comment by Xiguinilster** [comment]
I want to be able to extract the economy statistics of teams and players from files (Pov) recorded with rcon
