### ISSUE TITLE
I cant analyze demo/ wnukk

### ISSUE THREAD

**Issue by wnukk** [akiver/cs-demo-manager#938]
### Describe the bug

UNKNOWN

### Demo links

1-49c75d44-00c6-4b64-bdba-44adb6571864-1-1.dem

### Steps to reproduce

d

### Expected behavior

d

### How often does this bug happen?

Every time

### Log file

Grenade nil in decoy start event
Grenade nil in decoy start event
Command failed: psql -c "\copy matches(checksum,game,demo_path,name,date,source,type,map_name,server_name,client_name,tick_count,tickrate,framerate,duration,network_protocol,build_number,game_type,game_mode,game_mode_str,is_ranked,kill_count,assist_count,death_count,shot_count,winner_name,winner_side,overtime_count,max_rounds,has_vac_live_ban) FROM 'C:\Users\Carlos\AppData\Local\Temp\cs-demo-manager\1-49c75d44-00c6-4b64-bdba-44adb6571864-1-1_match.csv' ENCODING 'UTF8' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
BŁĄD:  nieoczekiwane dane po ostatniej oczekiwanej kolumnie
KONTEKST:  COPY matches, line 1: "ea59b15548f23ecd,CS2,C:\Users\Carlos\Desktop\1-49c75d44-00c6-4b64-bdba-44adb6571864-1-1.dem,1-49c75d..."

Error: Command failed: psql -c "\copy matches(checksum,game,demo_path,name,date,source,type,map_name,server_name,client_name,tick_count,tickrate,framerate,duration,network_protocol,build_number,game_type,game_mode,game_mode_str,is_ranked,kill_count,assist_count,death_count,shot_count,winner_name,winner_side,overtime_count,max_rounds,has_vac_live_ban) FROM 'C:\Users\Carlos\AppData\Local\Temp\cs-demo-manager\1-49c75d44-00c6-4b64-bdba-44adb6571864-1-1_match.csv' ENCODING 'UTF8' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
BŁĄD:  nieoczekiwane dane po ostatniej oczekiwanej kolumnie
KONTEKST:  COPY matches, line 1: "ea59b15548f23ecd,CS2,C:\Users\Carlos\Desktop\1-49c75d44-00c6-4b64-bdba-44adb6571864-1-1.dem,1-49c75d..."

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)

### Environment information

d

### Additional context

d

**Comment by wnukk** [comment]
ERROR: Unexpected data after last expected column

**Comment by akiver** [comment]
follow the template and provide a link to download the demo
