### ISSUE TITLE
Can't play demo after "The Armory" Update

### ISSUE THREAD

**Issue by yueisme** [akiver/cs-demo-manager#939]
### Describe the bug

https://store.steampowered.com/news/app/730/view/4674264042200250912

When play demo, prompts 'Verify Integrity of Game Cache'
![image](https://github.com/user-attachments/assets/e54e47fa-fee9-4d24-866e-0eac4fa77364)

### Steps to reproduce

-

### Expected behavior

play demo

### How often does this bug happen?

Every time

### Environment information

-

**Comment by 1598266725** [comment]
Me too

**Comment by joshhoughton** [comment]
Managed to solve this by
