### ISSUE TITLE
Updata 3.9.1 erro!

### ISSUE THREAD

**Issue by Spturate** [akiver/cs-demo-manager#943]
### Describe the bug

I get an error when I launch the game after updating to version 3.9.1
![b84292b5b8d4dfa55e208604eeff28f1](https://github.com/user-attachments/assets/90334e85-7ad1-4301-b457-92066eca20a5)

https://github.com/user-attachments/assets/df2ca156-8fb2-46c2-b2a1-6acc3ae487e4

### Demo links

![b84292b5b8d4dfa55e208604eeff28f1](https://github.com/user-attachments/assets/90334e85-7ad1-4301-b457-92066eca20a5)

https://github.com/user-attachments/assets/df2ca156-8fb2-46c2-b2a1-6acc3ae487e4

### Steps to reproduce

![b84292b5b8d4dfa55e208604eeff28f1](https://github.com/user-attachments/assets/90334e85-7ad1-4301-b457-92066eca20a5)

https://github.com/user-attachments/assets/df2ca156-8fb2-46c2-b2a1-6acc3ae487e4

### Expected behavior

Generate video erro

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/user-attachments/files/17265404/csdm.log)

### Environment information

Version: 3.9.1
OS: win32 x64 10.0.22631
Electron: 31.6.0
Chrome: 126.0.6478.234
Last database migrations:
v5 - 2024-10-04T23:02:39.287Z

### Additional context

122

**Comment by akiver** [comment]
The last CS2 update broke HLAE, you will have to wait for a new HLAE version that fix it.
Closing it since it's not a CS:DM issue, please open an issue on the HLAE repo instead.

**Comment by akiver** [comment]
A new version that fixes the issue has been released https://github.com/advancedfx/advancedfx/releases/tag/v2.172.3
