### ISSUE TITLE
HOOK script error

### ISSUE THREAD

**Issue by Chu-Xin-r** [akiver/cs-demo-manager#948]
### Describe the bug

I used the latest version 3.9.1 software on October 8, 2024, and encountered a HOOK script error while generating a video

### Steps to reproduce

![96937f135817f6a5910aa46de0749fe9](https://github.com/user-attachments/assets/4dc6ce56-59e1-4bbd-88fc-c93e6989a107)
![b2d048c1ec8efcc67003d6f22784d7b8](https://github.com/user-attachments/assets/0942d5d0-a8f6-4a5d-832b-a8fe2750ce83)

### Expected behavior

Normally, it should be possible to start recording, but I don't know why an error occurred

### How often does this bug happen?

Every time

### Environment information

Equipment name DESKTOP-GOI90VL
Processor 12th Gen Intel (R) Core (TM) i5-12400F 2.50 GHz
Built in RAM 32.0 GB (31.8 GB available)
Device ID 90062495-A0CB-4E03-ADF2-424F72418306
Product ID 00331-10000-00001-AA888
System type: 64 bit operating system, based on x64 processor

**Comment by akiver** [comment]
duplicate https://github.com/akiver/cs-demo-manager/issues/943
