### ISSUE TITLE
Steam not running

### ISSUE THREAD

**Issue by hasassnz** [akiver/cs-demo-manager#950]
### Describe the bug

![5fca6f1cca35233f7f214073dbc1efb](https://github.com/user-attachments/assets/fe5d0f31-77a0-4944-9520-89636b9e30c1)

Steam already running and CS was installed . still not found the Steam

### Steps to reproduce

1.start steam
2.start CSDM

### Expected behavior

Steam not found

### How often does this bug happen?

Every time

### Log file

![0d97b214274f73e3b325dedb4655abf](https://github.com/user-attachments/assets/972b17e9-94e7-408e-9548-385828758598)

### Environment information

Version 3.9.1 and oldest version does

**Comment by akiver** [comment]
This error means the process `steam.exe` is not running - you have to be connected to your Steam account.
Could you check that it's running from the Task Manager?
You should have an entry `steam.exe`:
![s](https://github.com/user-attachments/assets/97fed2d6-14af-4673-a6db-36d8563ebab0)

**Comment by hasassnz** [comment]
working .
![60691fc6a9e9f3a6f063379ee062e86](https://github.com/user-attachments/assets/24ae5f86-6e9b-431d-b4d2-88c2425b3a28)
![0883550a89c74a802a5011ed9d39f91](https://github.com/user-attachments/assets/bc71023d-0566-497d-820f-4ffbac5d75a8)
![3240e2637ef180115f1f4575dc8b448](https://github.com/user-attachments/assets/9c7c6671-0e6a-48e5-b2b7-47821f688d0d)
Win10 22H2

**Comment by akiver** [comment]
Could you upload the log file instead of a screenshot?

**Comment by hasassnz** [comment]
[csdm.log](https://github.com/user-attachments/files/17413746/csdm.log)

**Comment by akiver** [comment]
are you running steam with admin rights? this could be the issue.
i will add some debugging logs in the next version but it's probably an issue related to your setup as other users and I don't have this problem.

**Comment by hasassnz** [comment]
i got no idea .I also think it's a user permissions issue but the problem still occurs even after I switched to a standard user. maybe the next version will include an option for a custom installation path and a check for Steam's custom path i think.

**Comment by akiver** [comment]
does it work if you run the application with admin rights?
the problem is not about the Steam location but the fact that the app can't detect if it's running or not

**Comment by hasassnz** [comment]
steam and csdm run with & without admin all i try .  No . problem still there.  5eplay and prefectworld client can found steam . only csdm cant . Maybe i should reinstall system to try.

**Comment by akiver** [comment]
@hasassnz  could you try with the new version? I added some logs.

**Comment by hasassnz** [comment]
[csdm.log](https://github.com/user-attachments/files/18270147/csdm.log)
3.11.0 ， QS still there , not good

**Comment by akiver** [comment]
the folder `C:\\Windows\\system32` where `tasklist` is located is not in your `PATH` environment variable.
that's why it fails to detect the steam process - you must add it manually to fix the issue.
