### ISSUE TITLE
"Process not found." CSGO LEGACY

### ISSUE THREAD

**Issue by Aloncheeto** [akiver/cs-demo-manager#951]
### Describe the bug

whenever i try to record the demo highlights i get this error 
![image](https://github.com/user-attachments/assets/4c4bbb21-c8fd-4d34-a75d-2ff1d34fc9c5)

### Demo links

https://www.mediafire.com/file/3d9tczxepowp6c5/2024-10-17_00-11-42_282_de_cbble_pro-mod.dem/file

### Steps to reproduce

Start CS DM
Analyze demo (force valve type)
generate kill sequence of anyone
try to generate video

### Expected behavior

I would expect for the video to render properly.

### How often does this bug happen?

Every time

### Log file

[csdm.log](https://github.com/user-attachments/files/17407909/csdm.log)

### Environment information

Version: 3.9.1
OS: win32 x64 10.0.19045
Electron: 31.6.0
Chrome: 126.0.6478.234
Last database migrations:
v5 - 2024-10-17T03:54:00.365Z

### Additional context

I am not completely sure if csgo is still supported but the web seemed to indicate so.

**Comment by akiver** [comment]
fixed in https://github.com/akiver/cs-demo-manager/commit/1d6667c3c50ae940d05e691a903abd29027e84c2
