### ISSUE TITLE
Can't see who is talking when watching demos (from faceit at least)

### ISSUE THREAD

**Issue by pebskij** [akiver/cs-demo-manager#958]
### Describe the bug

Since like 1 month ago when I watch demos downloaded from Faceit, I can't see in the chat who is talking in voice.

### Steps to reproduce

worked previously but no longer

### Expected behavior

worked previously but no longer

### How often does this bug happen?

None

### Environment information

worked previously but no longer

**Comment by jacko1994** [comment]
The same

**Comment by akiver** [comment]
it's a CS2 bug, I added a note about it here https://cs-demo-manager.com/docs/guides/playback#player-voice-indicator-are-not-displayed-in-the-hud
