### ISSUE TITLE
HLTV 2.1

### ISSUE THREAD

**Issue by HaVoCiwnl** [akiver/cs-demo-manager#962]
### What problem is this solving

latest hltv 2.1 stats

### Proposed solution

extra line like for htlv 2.0

**Comment by akiver** [comment]
HLTV keeps the formula private and there is no plan to reverse-engineer it.
I added a note about it in the [doc](https://cs-demo-manager.com/docs/guides/demos-analysis#hltv-rating-21-support)

**Comment by HaVoCiwnl** [comment]
ah i didnt know that, fair enough.
