### ISSUE TITLE
Highlights and lowlights not working

### ISSUE THREAD

**Issue by syko** [akiver/cs-demo-manager#963]
### Describe the bug

Watching highlights/lowlights no longer works. Instead it seems to work like the "Watch Rounds" feature where the round simply ends when the given player dies.

I'm fairly certain it's a bug in a newer version of CS Demo Manager and not because of a CS update.

### Steps to reproduce

1. Open Matches tab
2. Double click to open a match
3. Right-click on a player
4. Choose "Watch" -> "Highlights" / "Lowlights" -> "Player POV" / "Enemy POV"
6. Observe the severe lack of selected lights :(

### Expected behavior

I would expect to see the short compilation of highlights or lowlights as selected.

### How often does this bug happen?

Every time

### Environment information

Version: 3.10.0
OS: win32 x64 10.0.22631
Electron: 33.2.0
Chrome: 130.0.6723.118
Last database migrations:
v6 - 2024-11-18T18:05:20.188Z
v5 - 2024-10-20T14:30:21.483Z
v4 - 2024-06-30T13:37:08.759Z
v3 - 2024-06-04T23:16:12.681Z
v2 - 2024-05-10T21:48:05.252Z

**Comment by jdwede** [comment]
Also experiencing this.
