### ISSUE TITLE
Analysis includes kills from before round start

### ISSUE THREAD

**Issue by milkywayfarer** [akiver/cs-demo-manager#965]
### Describe the bug

When analyzing a demo, I looked at the result in DB and discovered that:

1. In table `rounds`, round 1 starts at tick 6834; freeze time stops at tick 9317
2. In table `kills`, round 1 has kills before said ticks (starting from 0, that's the warmup period)

This yields unexpected results: warmup kills gets included in the first round, thus rating and kill counts are inaccurate.

### Demo links

https://drive.google.com/file/d/1u_cAGZD77TqRj-_aHieDeAxPLT2YLFbV/view?usp=sharing

### Steps to reproduce

1. Analyze the demo, get `match_checksum`
2. Connect to Postgres using the software of your choice
3. `select * from kills where round_number = 1 and match_checksum = $1`
4. `select * from rounds where number = 1 and match_checksum = $1`

### Expected behavior

I expect that every event that was caught before the round starts does not count towards the end analysis result.

### How often does this bug happen?

Every time

### Environment information

Version: 3.10.1
OS: darwin x64 24.0.0
Electron: 33.2.0
Chrome: 130.0.6723.118
Last database migrations:
v6 - 2024-11-18T07:38:14.896Z
v5 - 2024-08-21T06:10:44.808Z
v4 - 2024-08-08T16:29:56.767Z
v1 - 2024-08-08T16:29:20.861Z

**Comment by akiver** [comment]
https://github.com/akiver/cs-demo-manager/issues/751
