### ISSUE TITLE
Added "quick kill streak" event

### ISSUE THREAD

**Issue by WangChuDi** [akiver/cs-demo-manager#977]
### What problem is this solving

Multiple kills in a single turn can be found in the Search tab, but these kills may be spaced out over a long period of time. Adding a “fast kill streak” event can be used to distinguish between situations like sweeps or skewers.
![image](https://github.com/user-attachments/assets/3a549ed9-9668-472d-b06e-8225580951db)

### Proposed solution

You can determine if it is a fast kill streak by judging the kill tick interval or kill time interval.

**Comment by akiver** [comment]
the next version will show how long multikills took in the results.

![2024-12-16 at 00 28 29](https://github.com/user-attachments/assets/1d1c5bbb-fa69-4979-9ba4-103213c77156)

if you want more control over the filters, please use an SQL query, I added an example in [the doc](https://cs-demo-manager.com/docs/guides/export#find-quick-multi-kills)
