### ISSUE TITLE
Video generation ends too early before round ends/player dead after the update

### ISSUE THREAD

**Issue by Bubbl666** [akiver/cs-demo-manager#989]
### Describe the bug

Thank you so much for adding this feature in the latest update: feat(video): add input to change seconds delay before/after round start/end [#927](https://github.com/akiver/cs-demo-manager/issues/927)

I tested it and couldn't find where to adjust the delay in seconds before or after the round start or end. After generating three of my demos, I noticed that the video ends a few seconds too early, cutting off before the round finishes or the player dies.

Thank you for taking the time to look into this issue! 😊 Happy holidays! 

### Steps to reproduce

1. start the application
2. find any demos, open, on any players right-click generate videos, rounds
3. add to queue

### Expected behavior

I expected the video generation to end after the player dies or the round concludes, as it did before the v3.11.0 update.
Currently the video generation ends few seconds early.

### How often does this bug happen?

Every time

### Environment information

NA

**Comment by messioso** [comment]
Just noticed I'm also having this issue, i set +2 seconds but it ends before the round end/player dies when generating the sequence for player - rounds.

**Comment by Bubbl666** [comment]
> Just noticed I'm also having this issue, i set +2 seconds but it ends before the round end/player dies when generating the sequence for player - rounds.

I couldn't find where to set the time. Could you point it out please?

**Comment by messioso** [comment]
If you go to Generate player sequences -> pick your player -> event: round -> you can set a time to start before round starts and after player ends/player death.

It isn't available for kill or death

**Comment by Bubbl666** [comment]
Thank you so much! I found it. I'll give it a try and see if I can figure it out without bothering Akiver too much.

**Comment by messioso** [comment]
After testing again, all videos I've made today with the new 3.11.0 version with +2 seconds now all end too early.

**Comment by Bubbl666** [comment]
Issue resolved by adding 2-3 seconds after round finishes, thank you for the update again!
